import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
const db=supabase as any;
export type Collaborator={id:string;name:string;job_title:string|null;phone:string|null;commission_percent:number|string;commission_active:boolean;active:boolean;notes:string|null;created_at:string;updated_at:string};
export type CollaboratorDirectoryItem={id:string;name:string;job_title:string|null;active:boolean};
export type CommissionEntry={id:string;work_order_service_id:string;work_order_id:string;order_number:number;collaborator_id:string;collaborator_name:string;service_description:string;service_amount:number|string;commission_percent:number|string;commission_amount:number|string;earned_at:string;status:"pendente"|"pago"|"cancelado";paid_at:string|null};
function asError(error:unknown,fallback:string){if(error instanceof Error)return error;if(error&&typeof error==="object"&&"message" in error)return new Error(String((error as any).message??fallback));return new Error(fallback)}
export function useCollaborators(){return useQuery({queryKey:["collaborators","financial"],queryFn:async()=>{const {data,error}=await db.from("collaborators").select("*").order("name");if(error)throw asError(error,"Não foi possível carregar os colaboradores.");return (data??[]) as Collaborator[]}})}
export function useCollaboratorDirectory(){return useQuery({queryKey:["collaborators","directory"],queryFn:async()=>{const {data,error}=await db.from("collaborators").select("id,name,job_title,active").eq("active",true).order("name");if(error)throw asError(error,"Não foi possível carregar a lista de colaboradores.");return (data??[]) as CollaboratorDirectoryItem[]}})}
export function useWorkOrderCommissionEntries(workOrderId:string|null,enabled=true){return useQuery({queryKey:["commissions","work_order",workOrderId],enabled:Boolean(workOrderId)&&enabled,queryFn:async()=>{if(!workOrderId)return[];const {data,error}=await db.from("service_commission_entries").select("id,work_order_service_id,work_order_id,order_number,collaborator_id,collaborator_name,service_description,service_amount,commission_percent,commission_amount,earned_at,status,paid_at").eq("work_order_id",workOrderId).order("earned_at");if(error)throw asError(error,"Não foi possível carregar as comissões desta OS.");return (data??[]) as CommissionEntry[]}})}
export async function updateServiceExecution(input:{serviceId:string;collaboratorId:string|null;status:string}){const patch:any={collaborator_id:input.collaboratorId,status:input.status};if(input.status==="concluido")patch.completed_at=new Date().toISOString();else if(input.status!=="concluido")patch.completed_at=null;const {data,error}=await db.from("work_order_services").update(patch).eq("id",input.serviceId).select("id,work_order_id,collaborator_id,status,completed_at").single();if(error)throw asError(error,"Não foi possível atualizar o responsável e o andamento do serviço.");return data}
