import { supabase } from "@/integrations/supabase/client";
const db=supabase as any;
export type PurchaseInvoiceItemDraft={id:string;inventoryItemId:string;supplierCode:string;ean:string;ncm:string;cfop:string;description:string;unit:string;quantity:number;unitCost:number;salePrice:number;category?:string;minQuantity?:number;location?:string;sku?:string;barcode?:string};
export type ParsedPurchaseInvoice={supplierName:string;supplierCnpj:string;invoiceNumber:string;series:string;accessKey:string;issuedAt:string;totalAmount:number;items:PurchaseInvoiceItemDraft[]};
function descendants(node:Element|Document,localName:string){return Array.from(node.getElementsByTagName("*")).filter(el=>el.localName===localName)}
function firstText(node:Element|Document,localName:string){return descendants(node,localName)[0]?.textContent?.trim()??""}
function safeNumber(value:string|null|undefined){const n=Number(String(value??"0").replace(",","."));return Number.isFinite(n)?n:0}
function normalizeUnit(unit:string){const v=unit.trim().toLowerCase();if(["un","und","unid","unidade"].includes(v))return"un";if(["lt","l","litro","litros"].includes(v))return"l";if(v==="ml")return"ml";if(["kg","quilo"].includes(v))return"kg";if(["cx","caixa"].includes(v))return"cx";if(["m","metro"].includes(v))return"m";return v||"un"}
export async function parseNfeXml(file:File):Promise<ParsedPurchaseInvoice>{const xmlText=await file.text();const xml=new DOMParser().parseFromString(xmlText,"application/xml");if(xml.getElementsByTagName("parsererror").length)throw new Error("O XML não pôde ser lido. Verifique se este é o arquivo XML original da NF-e.");const inf=descendants(xml,"infNFe")[0];if(!inf)throw new Error("Este arquivo não parece ser um XML de NF-e válido.");const emit=descendants(inf,"emit")[0],ide=descendants(inf,"ide")[0],total=descendants(inf,"ICMSTot")[0],accessKey=(inf.getAttribute("Id")??"").replace(/^NFe/i,"").replace(/\D/g,"");const items=descendants(inf,"det").map(det=>{const prod=descendants(det,"prod")[0]??det,quantity=safeNumber(firstText(prod,"qCom")),unitCost=safeNumber(firstText(prod,"vUnCom")),lineTotal=safeNumber(firstText(prod,"vProd")),effective=unitCost||(quantity>0?lineTotal/quantity:0),eanRaw=firstText(prod,"cEAN")||firstText(prod,"cEANTrib"),ean=/^\d+$/.test(eanRaw)?eanRaw:"";return{id:crypto.randomUUID(),inventoryItemId:"",supplierCode:firstText(prod,"cProd"),ean,ncm:firstText(prod,"NCM"),cfop:firstText(prod,"CFOP"),description:firstText(prod,"xProd"),unit:normalizeUnit(firstText(prod,"uCom")),quantity,unitCost:effective,salePrice:effective}});return{supplierName:firstText(emit??inf,"xNome"),supplierCnpj:firstText(emit??inf,"CNPJ")||firstText(emit??inf,"CPF"),invoiceNumber:firstText(ide??inf,"nNF"),series:firstText(ide??inf,"serie"),accessKey,issuedAt:firstText(ide??inf,"dhEmi")||firstText(ide??inf,"dEmi"),totalAmount:safeNumber(firstText(total??inf,"vNF")),items}}
function safeFileName(name:string){return name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").toLowerCase()}
export async function uploadPurchaseInvoiceSource(invoiceId:string,file:File){if(file.size>20*1024*1024)throw new Error("O arquivo da nota pode ter no máximo 20 MB.");const path=`${invoiceId}/original-${safeFileName(file.name)}`;const options=file.type?{cacheControl:"3600",upsert:false,contentType:file.type}:{cacheControl:"3600",upsert:false};const {error}=await supabase.storage.from("purchase-invoices").upload(path,file,options);if(error)throw error;return path}
export async function importPurchaseInvoice(input:{sourceType:"xml"|"printed"|"manual";sourceFile?:File|null;supplierName:string;supplierCnpj?:string;invoiceNumber:string;series?:string;accessKey?:string;issuedAt?:string;notes?:string;createExpense:boolean;dueDate?:string;paid?:boolean;items:PurchaseInvoiceItemDraft[]}){const invoiceId=crypto.randomUUID();let sourceFilePath:string|null=null;try{if(input.sourceFile)sourceFilePath=await uploadPurchaseInvoiceSource(invoiceId,input.sourceFile);const p_invoice={id:invoiceId,source_type:input.sourceType,supplier_name:input.supplierName.trim(),supplier_cnpj:input.supplierCnpj?.trim()||"",invoice_number:input.invoiceNumber.trim(),series:input.series?.trim()||"",access_key:input.accessKey?.trim()||"",issued_at:input.issuedAt||"",source_file_path:sourceFilePath??"",notes:input.notes?.trim()||"",create_expense:input.createExpense,due_date:input.createExpense?input.dueDate||"":"",paid:Boolean(input.paid)};const p_items=input.items.map(i=>({inventory_item_id:i.inventoryItemId||"",supplier_code:i.supplierCode||"",ean:i.ean||"",ncm:i.ncm||"",cfop:i.cfop||"",description:i.description.trim(),unit:i.unit||"un",quantity:i.quantity,unit_cost:i.unitCost,sale_price:i.salePrice,category:i.category||"",min_quantity:i.minQuantity??0,location:i.location||"",sku:i.sku||"",barcode:i.barcode||i.ean||""}));const {data,error}=await db.rpc("post_purchase_invoice",{p_invoice,p_items});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return{id:String(row?.purchase_invoice_id??invoiceId),expenseId:row?.expense_id??null,itemCount:Number(row?.item_count??p_items.length),totalAmount:Number(row?.total_amount??0)}}catch(error){if(sourceFilePath)await supabase.storage.from("purchase-invoices").remove([sourceFilePath]);throw error}}
export async function openPurchaseInvoiceSource(path:string){const {data,error}=await supabase.storage.from("purchase-invoices").createSignedUrl(path,600);if(error||!data?.signedUrl)throw error??new Error("Não foi possível abrir o arquivo.");window.open(data.signedUrl,"_blank","noopener,noreferrer")}
