import { BRAND } from "@/lib/brand";

type Kind = "os" | "orcamento" | "recibo";
export type WorkOrderDocumentPayload = { order:any; services:any[]; parts:any[]; payments:any[] };
const esc=(v:unknown)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const brl=(v:unknown)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v??0));
const date=(v:unknown)=>{if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("pt-BR")};

export function printWorkOrderDocument(payload:WorkOrderDocumentPayload,kind:Kind){
 const {order,services,parts,payments}=payload;const c=order.customers??{},v=order.vehicles??{};
 const confirmed=payments.filter(p=>["confirmado","pago"].includes(String(p.status)));const paid=confirmed.reduce((s,p)=>s+Number(p.amount??0),0);const latest=confirmed.at(-1);
 const logo=typeof window!=="undefined"?new URL(BRAND.logoUrl,window.location.origin).href:BRAND.logoUrl;
 const rows=[...services.map(x=>({type:"SERV",desc:x.description,q:x.quantity,u:x.unit_price})),...parts.map(x=>({type:"PEÇA",desc:x.description,q:x.quantity,u:x.unit_price}))];
 const table=rows.length?rows.map(x=>`<tr><td>${esc(x.q)}</td><td>${x.type}</td><td>${esc(x.desc)}</td><td class="n">${brl(x.u)}</td><td class="n">${brl(Number(x.q)*Number(x.u))}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Nenhum item lançado.</td></tr>`;
 const body=kind==="recibo"?`<section class="receipt"><img src="${logo}"/><h1>RECIBO</h1><div class="big">${brl(latest?.amount??paid)}</div><p>Recebemos de <b>${esc(c.name||"—")}</b> o valor acima referente à <b>OS #${esc(order.order_number)}</b>.</p><div class="grid"><div><small>Veículo</small><b>${esc(`${v.brand??""} ${v.model??""}`)}</b></div><div><small>Placa</small><b>${esc(v.plate||"—")}</b></div><div><small>Forma</small><b>${esc(latest?.method||"—")}</b></div><div><small>Data</small><b>${date(latest?.paid_at||new Date())}</b></div></div><p>Total registrado: <b>${brl(paid)}</b></p><div class="sign">Assinatura / responsável ${esc(BRAND.shortName)}</div></section>`:
 `<section class="sheet"><header><img src="${logo}"/><div><b>${kind==="os"?"ORDEM DE SERVIÇO":"ORÇAMENTO"}</b><span> Nº ${esc(order.order_number)}</span><small>${date(order.entry_at)}</small></div></header><div class="info"><div><small>Cliente</small><b>${esc(c.name||"—")}</b></div><div><small>Telefone</small><b>${esc(c.phone||"—")}</b></div><div><small>Veículo</small><b>${esc(`${v.brand??""} ${v.model??""}`)}</b></div><div><small>Placa</small><b>${esc(v.plate||"—")}</b></div><div><small>KM entrada</small><b>${esc(order.mileage_in?`${Number(order.mileage_in).toLocaleString("pt-BR")} km`:"—")}</b></div><div><small>Combustível</small><b>${esc(order.fuel_level||"—")}</b></div></div><table><thead><tr><th>QTD</th><th>TIPO</th><th>DESCRIÇÃO</th><th>UNIT.</th><th>TOTAL</th></tr></thead><tbody>${table}</tbody></table><div class="totals"><p>Serviços <b>${brl(order.subtotal_services)}</b></p><p>Peças <b>${brl(order.subtotal_parts)}</b></p><p>Desconto <b>${brl(order.discount)}</b></p><p class="grand">TOTAL <b>${brl(order.total)}</b></p></div><div class="notes"><small>RELATO / OBSERVAÇÕES</small><p>${esc(order.customer_report||order.customer_notes||"")||"&nbsp;"}</p></div><div class="signatures"><span>Cliente / responsável</span><span>${esc(BRAND.name)}</span></div></section>`;
 const popup=window.open("","_blank","width=980,height=900");if(!popup)throw new Error("Libere pop-ups para imprimir ou salvar o documento em PDF.");
 popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(BRAND.shortName)} - OS ${esc(order.order_number)}</title><style>*{box-sizing:border-box}body{margin:0;background:#eee;font-family:Arial;color:#111}.sheet,.receipt{width:210mm;min-height:297mm;margin:12px auto;background:#fff;padding:12mm;box-shadow:0 4px 20px #0002}.receipt{width:148mm;min-height:auto}.sheet header{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #111;padding-bottom:12px}.sheet header img,.receipt img{width:235px;max-width:60%;height:auto}.sheet header div{text-align:right}.sheet header b{display:block;font-size:18px}.sheet header small{display:block;margin-top:4px}.info{display:grid;grid-template-columns:1fr 1fr 1fr;margin-top:14px;border:1px solid #999}.info>div{padding:8px;border-right:1px solid #bbb;border-bottom:1px solid #bbb}.info small,.grid small,.notes small{display:block;font-size:8px;text-transform:uppercase;color:#666;margin-bottom:3px}.info b{font-size:11px}table{width:100%;border-collapse:collapse;margin-top:12px;font-size:11px}th{background:#111214;color:#fff;padding:8px;text-align:left}td{border:1px solid #999;padding:7px}.n{text-align:right}.empty{text-align:center;color:#777}.totals{width:300px;margin:12px 0 0 auto}.totals p{display:flex;justify-content:space-between;margin:0;border:1px solid #aaa;border-bottom:0;padding:7px;font-size:11px}.totals .grand{background:#111214;color:#fff;font-size:14px;border-color:#111214}.notes{margin-top:16px;border:1px solid #aaa;padding:9px;min-height:65px}.notes p{white-space:pre-wrap;font-size:11px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:35px;margin-top:45px}.signatures span,.sign{border-top:1px solid #111;text-align:center;padding-top:6px;font-size:9px}.receipt h1{margin-top:25px;border-bottom:2px solid #111;padding-bottom:8px}.receipt .big{font-size:30px;font-weight:900;color:#B97900}.receipt p{font-size:12px;line-height:1.6}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.grid>div{background:#f5f5f5;padding:9px}.sign{margin-top:50px}.print{position:fixed;right:20px;top:20px;background:#F0B323;color:#111;border:0;border-radius:10px;padding:12px 18px;font-weight:900;cursor:pointer}@media print{body{background:#fff}.sheet,.receipt{margin:0;box-shadow:none;width:auto;min-height:auto;padding:8mm}.print{display:none}@page{size:A4 portrait;margin:7mm}}</style></head><body><button class="print" onclick="window.print()">Imprimir / Salvar PDF</button>${body}<script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250))</script></body></html>`);popup.document.close();
}
