import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Car, CheckCircle2, Clock3, Loader2, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { BRAND } from "@/lib/brand";

export const Route = createFileRoute("/acompanhar/$token")({ component: TrackingPage });
const steps=["recepcao","diagnostico","aguardando_aprovacao","em_execucao","finalizacao","pronto_entrega","entregue"];
const labels:any={recepcao:"Recepção",diagnostico:"Diagnóstico",aguardando_aprovacao:"Aguardando aprovação",em_execucao:"Em execução",finalizacao:"Finalização",pronto_entrega:"Pronto para retirada",entregue:"Entregue",cancelada:"Cancelada"};
function TrackingPage(){const {token}=Route.useParams();const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{void supabase.rpc("get_vehicle_tracking" as any,{p_token:token} as any).then(({data,error})=>{if(error)setError(error.message);else setData(data);setLoading(false)})},[token]);if(loading)return <Shell><Loader2 className="mx-auto size-9 animate-spin text-[#F0B323]"/><p className="mt-4 text-center text-white/45">Carregando acompanhamento...</p></Shell>;if(error||!data)return <Shell><p className="text-center text-xl font-black">Acompanhamento não encontrado</p><p className="mt-2 text-center text-white/45">Confira se o link recebido está correto.</p></Shell>;const status=data.tracking?.status||data.order?.status||"recepcao";const idx=steps.indexOf(status);return <Shell><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Acompanhamento da OS</p><h1 className="mt-2 text-3xl font-black">Olá, {data.customer?.name||"cliente"}</h1></div><img src={BRAND.iconUrl} className="size-20 rounded-2xl" alt=""/></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info icon={Car} title="Veículo" text={`${data.vehicle?.brand||""} ${data.vehicle?.model||""} • ${data.vehicle?.plate||""}`}/><Info icon={Wrench} title="Status atual" text={labels[status]||status}/></div><div className="mt-8 rounded-2xl border border-white/8 bg-white/[.025] p-5"><h2 className="font-black">Etapas do serviço</h2><div className="mt-5 space-y-3">{steps.map((step,i)=>{const done=idx>=i;return <div key={step} className="flex items-center gap-3"><div className={`flex size-9 items-center justify-center rounded-full ${done?"bg-[#F0B323] text-black":"bg-white/8 text-white/30"}`}>{done?<CheckCircle2 className="size-5"/>:<Clock3 className="size-4"/>}</div><span className={done?"font-bold text-white":"text-white/35"}>{labels[step]}</span></div>})}</div></div>{data.tracking?.customer_note&&<div className="mt-5 rounded-2xl border border-[#F0B323]/20 bg-[#F0B323]/8 p-5"><p className="text-xs font-black uppercase tracking-wider text-[#F0B323]">Mensagem da oficina</p><p className="mt-2 leading-7 text-white/75">{data.tracking.customer_note}</p></div>}<Link to="/" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-white/45 hover:text-[#FFC43D]"><ArrowLeft className="size-4"/> Voltar ao site</Link></Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="compact-grid flex min-h-screen items-center justify-center bg-[#070707] px-4 py-10 text-white"><div className="w-full max-w-2xl rounded-[2rem] border border-[#F0B323]/18 bg-[#111214]/95 p-6 shadow-2xl sm:p-8">{children}</div></main>}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-black/25 p-4"><Icon className="size-5 text-[#F0B323]"/><p className="mt-3 text-xs uppercase tracking-wider text-white/35">{title}</p><p className="mt-1 font-black">{text}</p></div>}
