import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarCheck, Car, CheckCircle2, ClipboardList, Gauge, MessageCircle, ShieldCheck, Sparkles, Wrench, Clock3, SearchCheck, BadgeCheck, PackageSearch, WalletCards, Smartphone, Star, MapPin, Phone, FileText } from "lucide-react";
import { BRAND } from "@/lib/brand";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:`${BRAND.name} | Tecnologia e confiança para seu veículo`},{name:"description",content:"Centro automotivo com atendimento organizado, diagnóstico, orçamento, ordem de serviço digital e acompanhamento do veículo."}]}),
  component: HomePage,
});

const services = [
  {title:"Troca de óleo e filtros",text:"Lubrificação correta e troca preventiva para preservar o motor."},
  {title:"Freios",text:"Inspeção de pastilhas, discos, fluido e componentes do sistema."},
  {title:"Alinhamento e balanceamento",text:"Mais estabilidade, conforto e desgaste uniforme dos pneus."},
  {title:"Pneus",text:"Avaliação, troca, rodízio e conferência das condições de rodagem."},
  {title:"Mecânica em geral",text:"Diagnóstico e manutenção dos principais sistemas do veículo."},
  {title:"Elétrica automotiva",text:"Bateria, alternador, iluminação, chicotes e diagnóstico elétrico."},
  {title:"Embreagem",text:"Avaliação de desgaste, ruídos, trepidações e troca do conjunto."},
  {title:"Revisão e check-up geral",text:"Inspeção preventiva completa antes de viagens e revisões periódicas."},
];

const steps=[
  {icon:Car,title:"1. Recepção",text:"Cadastro do cliente e veículo, quilometragem, combustível, checklist e fotos."},
  {icon:SearchCheck,title:"2. Diagnóstico",text:"A equipe registra o diagnóstico e define os serviços e peças necessários."},
  {icon:FileText,title:"3. Orçamento",text:"Valores de peças e mão de obra são apresentados de forma organizada."},
  {icon:BadgeCheck,title:"4. Aprovação",text:"Somente depois da aprovação o serviço segue para execução."},
  {icon:Wrench,title:"5. Execução",text:"A OS acompanha cada etapa, profissional responsável e materiais utilizados."},
  {icon:CheckCircle2,title:"6. Entrega",text:"Conferência final, pagamento, garantia e histórico ficam vinculados ao veículo."},
];

function HomePage() {
  return <main className="min-h-screen bg-[#070707] text-white selection:bg-[#F0B323] selection:text-black">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/8 bg-[#070707]/88 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <a href="#inicio" className="flex items-center"><img src={BRAND.logoUrl} alt={BRAND.name} className="h-12 w-auto object-contain" /></a>
        <nav className="hidden items-center gap-7 text-sm font-semibold text-white/65 lg:flex"><a href="#servicos" className="hover:text-[#FFC43D]">Serviços</a><a href="#diferenciais" className="hover:text-[#FFC43D]">Diferenciais</a><a href="#processo" className="hover:text-[#FFC43D]">Como funciona</a><a href="#tecnologia" className="hover:text-[#FFC43D]">Tecnologia</a><a href="#contato" className="hover:text-[#FFC43D]">Contato</a></nav>
        <Link to="/login" className="rounded-xl border border-[#F0B323]/55 bg-[#F0B323]/10 px-4 py-2.5 text-sm font-black text-[#FFC43D] transition hover:bg-[#F0B323] hover:text-black">Área administrativa</Link>
      </div>
    </header>

    <section id="inicio" className="compact-grid relative overflow-hidden pt-20">
      <div className="absolute -left-24 top-20 size-80 rounded-full bg-[#F0B323]/10 blur-3xl"/><div className="absolute -right-24 bottom-0 size-[28rem] rounded-full bg-[#F0B323]/8 blur-3xl"/>
      <div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.08fr_.92fr] lg:px-8">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-[#F0B323]/25 bg-[#F0B323]/8 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-[#FFC43D]"><Sparkles className="size-4"/> Atendimento automotivo conectado</div><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.96] tracking-[-.05em] sm:text-6xl xl:text-7xl">Seu carro em boas mãos, <span className="compact-gold-text">do diagnóstico à entrega.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/58">Um centro automotivo moderno, com atendimento organizado, orçamento claro, histórico completo e acompanhamento digital do serviço.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contato" className="inline-flex items-center gap-2 rounded-2xl bg-[#F0B323] px-6 py-4 font-black text-black shadow-2xl shadow-amber-500/10 transition hover:bg-[#FFC43D]">Solicitar atendimento <ArrowRight className="size-5"/></a><a href="#servicos" className="rounded-2xl border border-white/12 bg-white/[.03] px-6 py-4 font-bold text-white/80 hover:border-[#F0B323]/45">Conhecer serviços</a></div><div className="mt-10 grid max-w-2xl grid-cols-3 gap-3"><MiniStat icon={ShieldCheck} title="Confiança" text="Histórico organizado"/><MiniStat icon={Gauge} title="Agilidade" text="Fluxo de OS digital"/><MiniStat icon={MessageCircle} title="Transparência" text="Cliente acompanha"/></div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="compact-glow rounded-[2rem] border border-[#F0B323]/22 bg-gradient-to-b from-[#171719] to-[#0c0c0d] p-5"><div className="rounded-[1.5rem] border border-white/8 bg-black/50 p-6"><img src={BRAND.iconUrl} alt="" className="compact-float mx-auto w-[62%] max-w-72"/><div className="mt-7 grid grid-cols-2 gap-3"><Feature icon={ClipboardList} title="Ordem de serviço" text="Fluxo completo"/><Feature icon={CalendarCheck} title="Agenda" text="Horários e retornos"/><Feature icon={Car} title="Veículos" text="Histórico por placa"/><Feature icon={Wrench} title="Oficina" text="Serviços e estoque"/></div></div></div></div>
      </div>
    </section>

    <section className="border-y border-white/8 bg-[#0c0c0e]"><div className="mx-auto grid max-w-7xl sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Mais segurança","Manutenção preventiva e registro do veículo"],[Wrench,"Serviço completo","Mecânica, elétrica, pneus, freios e revisão"],[ClipboardList,"Processo organizado","Cada etapa registrada até a entrega"],[MessageCircle,"Comunicação clara","Orçamento e andamento sem surpresa"]].map(([I,t,x]:any)=><div key={t} className="border-b border-white/8 p-7 sm:border-r lg:border-b-0"><I className="size-5 text-[#F0B323]"/><p className="mt-4 font-black">{t}</p><p className="mt-2 text-sm leading-6 text-white/42">{x}</p></div>)}</div></section>

    <section id="servicos" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Catálogo de serviços</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Tudo o que seu veículo precisa em um só lugar.</h2><p className="mt-5 text-base leading-7 text-white/48">Atendimento técnico com processo padronizado, registro do histórico e foco em segurança, clareza e confiança.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service,i)=><Link key={service.title} to="/servicos/$slug" params={{slug:["troca-de-oleo","freios","alinhamento-balanceamento","pneus","mecanica-geral","eletrica","embreagem","check-up"][i]}} className="group rounded-3xl border border-white/8 bg-white/[.025] p-6 transition hover:-translate-y-1 hover:border-[#F0B323]/35 hover:bg-white/[.04]"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/10 text-[#FFC43D]"><Wrench className="size-5"/></div><h3 className="mt-5 text-lg font-black">{service.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{service.text}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#F0B323]">Saiba mais <ArrowRight className="size-4"/></span></Link>)}</div></div></section>

    <section id="diferenciais" className="border-y border-white/8 bg-[#101012] py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Por que escolher</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Manutenção sem adivinhação e sem surpresa.</h2><p className="mt-6 text-lg leading-8 text-white/50">A experiência conecta recepção, diagnóstico, aprovação, execução e entrega para você saber o que o carro precisa e por quê.</p><div className="mt-8 space-y-3">{["Checklist de entrada e registro do veículo","Diagnóstico antes da execução","Orçamento e aprovação organizados","Histórico de serviços por veículo","Conferência final antes da entrega"].map(item=><div key={item} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4"><CheckCircle2 className="size-5 shrink-0 text-[#F0B323]"/><span className="font-semibold text-white/75">{item}</span></div>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><FeatureCard icon={SearchCheck} title="Diagnóstico responsável" text="Registro técnico para reduzir retrabalho e decisões no escuro."/><FeatureCard icon={ShieldCheck} title="Histórico preservado" text="Cada atendimento fica relacionado ao cliente e ao veículo."/><FeatureCard icon={Clock3} title="Previsão de entrega" text="A equipe acompanha prazos e serviços em andamento."/><FeatureCard icon={Smartphone} title="Acompanhamento digital" text="O cliente pode consultar o status da própria OS por link."/></div></div></section>

    <section id="processo" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Como funciona</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Um processo claro do primeiro contato à entrega.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{steps.map(({icon:I,title,text})=><div key={title} className="rounded-3xl border border-white/8 bg-[#111214] p-6"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#F0B323]/10 text-[#F0B323]"><I className="size-6"/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-white/45">{text}</p></div>)}</div></div></section>

    <section id="tecnologia" className="border-y border-white/8 bg-[#0d0d0f] py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Tecnologia aplicada</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Uma oficina moderna precisa de informação organizada.</h2><p className="mt-6 text-lg leading-8 text-white/50">O sistema COMPACT integra clientes, veículos, agenda, orçamentos, OS, estoque, financeiro, comissões e histórico em um único ambiente.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{[[ClipboardList,"OS digital"],[PackageSearch,"Estoque integrado"],[WalletCards,"Financeiro"],[CalendarCheck,"Agenda operacional"],[MessageCircle,"Acompanhamento"],[Users,"Clientes e equipe"]].map(([I,t]:any)=><div key={t} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4"><I className="size-5 text-[#F0B323]"/><span className="font-bold text-white/75">{t}</span></div>)}</div></div><div className="rounded-[2rem] border border-[#F0B323]/18 bg-gradient-to-br from-[#1b170f] to-[#0b0b0c] p-6 sm:p-8"><div className="rounded-3xl border border-white/8 bg-black/35 p-6"><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Painel administrativo</p><h3 className="mt-3 text-3xl font-black">Tudo conectado.</h3><div className="mt-7 space-y-3">{["Clientes e veículos com histórico","Orçamentos convertidos em OS","Fotos e checklist na recepção","Peças com baixa automática no estoque","Pagamentos, despesas e comissões","Entrada de nota fiscal e atualização de saldo"].map(x=><div key={x} className="flex items-center gap-3 border-b border-white/7 pb-3 text-sm text-white/65"><CheckCircle2 className="size-4 shrink-0 text-[#F0B323]"/>{x}</div>)}</div></div></div></div></section>

    <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-3xl text-center"><div className="flex justify-center gap-1">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-5 fill-[#F0B323] text-[#F0B323]"/>)}</div><h2 className="mt-5 text-3xl font-black sm:text-4xl">Mais confiança para o cliente. Mais controle para a oficina.</h2><p className="mt-4 text-base leading-7 text-white/48">Um atendimento organizado transmite profissionalismo e ajuda a construir relacionamento de longo prazo.</p></div></div></section>

    <section id="contato" className="pb-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="rounded-[2rem] border border-[#F0B323]/20 bg-gradient-to-r from-[#17130b] to-[#111214] p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.22em] text-[#F0B323]">Atendimento</p><h2 className="mt-4 max-w-3xl text-3xl font-black sm:text-4xl">Pronto para cuidar do seu veículo?</h2><p className="mt-3 max-w-2xl text-white/50">Entre em contato com a equipe para solicitar avaliação, revisão ou orçamento.</p><div className="mt-6 flex flex-wrap gap-4 text-sm text-white/55"><span className="inline-flex items-center gap-2"><Phone className="size-4 text-[#F0B323]"/> WhatsApp configurável por oficina</span><span className="inline-flex items-center gap-2"><MapPin className="size-4 text-[#F0B323]"/> Endereço configurável no painel</span></div></div><Link to="/login" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-2xl bg-[#F0B323] px-6 py-4 font-black text-black">Entrar no sistema <ArrowRight className="size-5"/></Link></div></div></div></section>

    <footer className="border-t border-white/8 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-sm text-white/35 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-3"><img src={BRAND.iconUrl} alt="" className="size-9 rounded-lg"/><span>© {new Date().getFullYear()} {BRAND.name}</span></div><span>Tecnologia, confiança e gestão para sua oficina.</span></div></footer>
  </main>;
}

function MiniStat({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><Icon className="size-5 text-[#F0B323]"/><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-xs text-white/38">{text}</p></div>}
function Feature({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><Icon className="size-5 text-[#F0B323]"/><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-xs text-white/35">{text}</p></div>}
function FeatureCard({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-3xl border border-white/8 bg-black/20 p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/10 text-[#F0B323]"><Icon className="size-5"/></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{text}</p></div>}
