import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, CalendarCheck, Car, CheckCircle2, ClipboardList, Clock3, FileText, Gauge, MessageCircle, PackageSearch, SearchCheck, ShieldCheck, Smartphone, Sparkles, Star, Users, WalletCards, Wrench, type LucideIcon } from "lucide-react";
import { BRAND } from "@/lib/brand";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:`${BRAND.name} | Tecnologia e confiança para seu veículo`},{name:"description",content:"Centro automotivo com atendimento organizado, diagnóstico, orçamento, ordem de serviço digital e acompanhamento do veículo."}]}),component:HomePage});

type InfoItem={icon:LucideIcon;title:string;text:string};
const services=[
 {slug:"troca-de-oleo",title:"Troca de óleo e filtros",text:"Lubrificação correta e troca preventiva para preservar o motor."},
 {slug:"freios",title:"Freios",text:"Inspeção de pastilhas, discos, fluido e componentes do sistema."},
 {slug:"alinhamento-balanceamento",title:"Alinhamento e balanceamento",text:"Mais estabilidade, conforto e desgaste uniforme dos pneus."},
 {slug:"pneus",title:"Pneus",text:"Avaliação, troca, rodízio e conferência das condições de rodagem."},
 {slug:"mecanica-geral",title:"Mecânica em geral",text:"Diagnóstico e manutenção dos principais sistemas do veículo."},
 {slug:"eletrica",title:"Elétrica automotiva",text:"Bateria, alternador, iluminação, chicotes e diagnóstico elétrico."},
 {slug:"embreagem",title:"Embreagem",text:"Avaliação de desgaste, ruídos, trepidações e troca do conjunto."},
 {slug:"check-up",title:"Revisão e check-up geral",text:"Inspeção preventiva completa antes de viagens e revisões periódicas."},
] as const;
const steps:InfoItem[]=[{icon:Car,title:"1. Recepção",text:"Cliente, veículo, quilometragem, combustível, checklist e fotos."},{icon:SearchCheck,title:"2. Diagnóstico",text:"A equipe registra o diagnóstico e define serviços e peças."},{icon:FileText,title:"3. Orçamento",text:"Peças e mão de obra apresentados de forma clara."},{icon:BadgeCheck,title:"4. Aprovação",text:"O serviço avança após a aprovação do cliente."},{icon:Wrench,title:"5. Execução",text:"A OS acompanha serviços, materiais e andamento."},{icon:CheckCircle2,title:"6. Entrega",text:"Conferência, pagamento, recibo e histórico do veículo."}];
const benefits:InfoItem[]=[{icon:ShieldCheck,title:"Mais segurança",text:"Manutenção preventiva e registro do veículo"},{icon:Wrench,title:"Serviço completo",text:"Mecânica, elétrica, pneus, freios e revisão"},{icon:ClipboardList,title:"Processo organizado",text:"Cada etapa registrada até a entrega"},{icon:MessageCircle,title:"Comunicação clara",text:"Orçamento e andamento sem surpresa"}];
const technologyItems:Array<{icon:LucideIcon;title:string}>=[{icon:ClipboardList,title:"OS digital"},{icon:PackageSearch,title:"Estoque integrado"},{icon:WalletCards,title:"Financeiro"},{icon:CalendarCheck,title:"Agenda operacional"},{icon:MessageCircle,title:"Acompanhamento"},{icon:Users,title:"Clientes e equipe"}];

function HomePage(){return <main className="min-h-screen bg-[#070707] text-white selection:bg-[#F0B323] selection:text-black">
<header className="fixed inset-x-0 top-0 z-50 border-b border-white/8 bg-[#070707]/88 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#inicio"><img src={BRAND.logoUrl} alt={BRAND.name} className="h-12 w-auto object-contain"/></a><nav className="hidden items-center gap-7 text-sm font-semibold text-white/65 lg:flex"><a href="#servicos" className="hover:text-[#FFC43D]">Serviços</a><a href="#diferenciais" className="hover:text-[#FFC43D]">Diferenciais</a><a href="#processo" className="hover:text-[#FFC43D]">Como funciona</a><a href="#tecnologia" className="hover:text-[#FFC43D]">Tecnologia</a><a href="#contato" className="hover:text-[#FFC43D]">Contato</a></nav><Link to="/login" className="rounded-xl border border-[#F0B323]/55 bg-[#F0B323]/10 px-4 py-2.5 text-sm font-black text-[#FFC43D] hover:bg-[#F0B323] hover:text-black">Área administrativa</Link></div></header>
<section id="inicio" className="compact-grid relative overflow-hidden pt-20"><div className="absolute -left-24 top-20 size-80 rounded-full bg-[#F0B323]/10 blur-3xl"/><div className="absolute -right-24 bottom-0 size-[28rem] rounded-full bg-[#F0B323]/8 blur-3xl"/><div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.08fr_.92fr] lg:px-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#F0B323]/25 bg-[#F0B323]/8 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-[#FFC43D]"><Sparkles className="size-4"/>Atendimento automotivo conectado</div><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.96] tracking-[-.05em] sm:text-6xl xl:text-7xl">Seu carro em boas mãos, <span className="compact-gold-text">do diagnóstico à entrega.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/58">Um centro automotivo moderno, com orçamento claro, histórico completo e acompanhamento digital do serviço.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contato" className="inline-flex items-center gap-2 rounded-2xl bg-[#F0B323] px-6 py-4 font-black text-black">Solicitar atendimento <ArrowRight className="size-5"/></a><a href="#servicos" className="rounded-2xl border border-white/12 bg-white/[.03] px-6 py-4 font-bold text-white/80">Conhecer serviços</a></div><div className="mt-10 grid max-w-2xl grid-cols-3 gap-3"><Mini icon={ShieldCheck} title="Confiança" text="Histórico organizado"/><Mini icon={Gauge} title="Agilidade" text="Fluxo de OS digital"/><Mini icon={MessageCircle} title="Transparência" text="Cliente acompanha"/></div></div><div className="relative mx-auto w-full max-w-xl"><div className="compact-glow rounded-[2rem] border border-[#F0B323]/22 bg-gradient-to-b from-[#171719] to-[#0c0c0d] p-5"><div className="rounded-[1.5rem] border border-white/8 bg-black/50 p-6"><img src={BRAND.iconUrl} alt="" className="compact-float mx-auto w-[62%] max-w-72"/><div className="mt-7 grid grid-cols-2 gap-3"><Feature icon={ClipboardList} title="Ordem de serviço" text="Fluxo completo"/><Feature icon={CalendarCheck} title="Agenda" text="Horários e retornos"/><Feature icon={Car} title="Veículos" text="Histórico por placa"/><Feature icon={Wrench} title="Oficina" text="Serviços e estoque"/></div></div></div></div></div></section>
<section className="border-y border-white/8 bg-[#0c0c0e]"><div className="mx-auto grid max-w-7xl sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({icon:Icon,title,text})=><div key={title} className="border-b border-white/8 p-7 sm:border-r lg:border-b-0"><Icon className="size-5 text-[#F0B323]"/><p className="mt-4 font-black">{title}</p><p className="mt-2 text-sm leading-6 text-white/42">{text}</p></div>)}</div></section>
<section id="servicos" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Heading eyebrow="Catálogo de serviços" title="Tudo o que seu veículo precisa em um só lugar." text="Atendimento técnico com processo padronizado, histórico e foco em segurança e clareza."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(service=><Link key={service.slug} to="/servicos/$slug" params={{slug:service.slug}} className="group rounded-3xl border border-white/8 bg-white/[.025] p-6 transition hover:-translate-y-1 hover:border-[#F0B323]/35"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/10 text-[#FFC43D]"><Wrench className="size-5"/></div><h3 className="mt-5 text-lg font-black">{service.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{service.text}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#F0B323]">Saiba mais <ArrowRight className="size-4"/></span></Link>)}</div></div></section>
<section id="diferenciais" className="border-y border-white/8 bg-[#101012] py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Por que escolher</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Manutenção sem adivinhação e sem surpresa.</h2><p className="mt-6 text-lg leading-8 text-white/50">Recepção, diagnóstico, aprovação, execução e entrega ficam conectados em um único processo.</p><div className="mt-8 space-y-3">{["Checklist de entrada e fotos","Diagnóstico antes da execução","Orçamento e aprovação organizados","Histórico por veículo","Conferência final antes da entrega"].map(item=><div key={item} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4"><CheckCircle2 className="size-5 shrink-0 text-[#F0B323]"/><span className="font-semibold text-white/75">{item}</span></div>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><FeatureCard icon={SearchCheck} title="Diagnóstico responsável" text="Registro técnico para reduzir retrabalho e decisões no escuro."/><FeatureCard icon={ShieldCheck} title="Histórico preservado" text="Cada atendimento fica vinculado ao cliente e veículo."/><FeatureCard icon={Clock3} title="Previsão de entrega" text="A equipe acompanha prazos e serviços em andamento."/><FeatureCard icon={Smartphone} title="Acompanhamento digital" text="O cliente consulta o status da própria OS por link."/></div></div></section>
<section id="processo" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Heading eyebrow="Como funciona" title="Um processo claro do primeiro contato à entrega."/><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{steps.map(({icon:Icon,title,text})=><div key={title} className="rounded-3xl border border-white/8 bg-[#111214] p-6"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#F0B323]/10 text-[#F0B323]"><Icon className="size-6"/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-white/45">{text}</p></div>)}</div></div></section>
<section id="tecnologia" className="border-y border-white/8 bg-[#0d0d0f] py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">Tecnologia aplicada</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Uma oficina moderna precisa de informação organizada.</h2><p className="mt-6 text-lg leading-8 text-white/50">A plataforma integra clientes, veículos, agenda, orçamentos, OS, estoque, financeiro, comissões e histórico.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{technologyItems.map(({icon:Icon,title})=><div key={title} className="flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4"><Icon className="size-5 text-[#F0B323]"/><span className="font-bold text-white/75">{title}</span></div>)}</div></div><div className="rounded-[2rem] border border-[#F0B323]/18 bg-gradient-to-br from-[#1b170f] to-[#0b0b0c] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Painel administrativo</p><h3 className="mt-3 text-3xl font-black">Tudo conectado.</h3><div className="mt-7 space-y-3">{["Clientes e veículos com histórico","Orçamentos convertidos em OS","Fotos e checklist na recepção","Peças com baixa automática no estoque","Pagamentos, despesas e comissões","Entrada de nota fiscal e atualização de saldo"].map(x=><div key={x} className="flex items-center gap-3 border-b border-white/7 pb-3 text-sm text-white/65"><CheckCircle2 className="size-4 shrink-0 text-[#F0B323]"/>{x}</div>)}</div></div></div></section>
<section className="py-24"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><div className="flex justify-center gap-1">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-5 fill-[#F0B323] text-[#F0B323]"/>)}</div><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black tracking-[-.04em]">Mais controle para a oficina. Mais confiança para o cliente.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/48">Tecnologia é útil quando deixa o atendimento mais simples, transparente e profissional.</p></div></section>
<section id="contato" className="pb-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="rounded-[2rem] border border-[#F0B323]/20 bg-gradient-to-r from-[#17130b] to-[#111214] p-8 sm:p-12"><p className="text-sm font-black uppercase tracking-[.22em] text-[#F0B323]">Atendimento</p><div className="mt-4 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="max-w-3xl text-3xl font-black sm:text-4xl">Pronto para cuidar do seu veículo?</h2><p className="mt-3 max-w-2xl text-white/50">Entre em contato com a oficina para agendar uma avaliação ou revisão.</p></div><a href="#inicio" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-2xl bg-[#F0B323] px-6 py-4 font-black text-black">Solicitar atendimento <ArrowRight className="size-5"/></a></div></div></div></section>
<footer className="border-t border-white/8 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-sm text-white/35 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© {new Date().getFullYear()} {BRAND.name}</span><span>Tecnologia, confiança e gestão.</span></div></footer>
</main>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.24em] text-[#F0B323]">{eyebrow}</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">{title}</h2>{text&&<p className="mt-5 text-base leading-7 text-white/48">{text}</p>}</div>}
function Mini({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><Icon className="size-5 text-[#F0B323]"/><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-xs text-white/38">{text}</p></div>}
function Feature({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><Icon className="size-5 text-[#F0B323]"/><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-xs text-white/35">{text}</p></div>}
function FeatureCard({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <div className="rounded-3xl border border-white/8 bg-black/25 p-6"><Icon className="size-6 text-[#F0B323]"/><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-white/45">{text}</p></div>}
