import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Eye, EyeOff, KeyRound, Loader2, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { BRAND } from "@/lib/brand";

export const Route=createFileRoute("/login")({component:LoginPage});

function LoginPage(){
 const navigate=useNavigate();
 const [mode,setMode]=useState<"login"|"first">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{if(data.session)navigate({to:"/admin",replace:true})}).catch(()=>{})},[navigate]);
 function switchMode(next:"login"|"first"){setMode(next);setPassword("");setConfirmPassword("");setError(null);setSuccess(null)}
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError(null);setSuccess(null);try{
   const normalized=email.trim().toLowerCase();
   if(!normalized)throw new Error("Informe o e-mail autorizado pela oficina.");
   if(mode==="login"){
     const {error}=await supabase.auth.signInWithPassword({email:normalized,password});if(error)throw error;navigate({to:"/admin",replace:true});return;
   }
   if(password.length<6)throw new Error("A senha precisa ter pelo menos 6 caracteres.");
   if(password!==confirmPassword)throw new Error("As senhas não coincidem.");
   const {data,error}=await supabase.auth.signUp({email:normalized,password});if(error)throw error;
   if(data.user&&Array.isArray(data.user.identities)&&data.user.identities.length===0)throw new Error("Este e-mail já possui acesso. Use a opção Entrar.");
   if(data.session){navigate({to:"/admin",replace:true});return;}
   setSuccess("Acesso criado. Se a confirmação por e-mail estiver habilitada, confirme o e-mail e depois entre normalmente.");
   setMode("login");setPassword("");setConfirmPassword("");
 }catch(err:any){const raw=err instanceof Error?err.message:"Não foi possível concluir.";const lower=raw.toLowerCase();if(lower.includes("não autorizado")||lower.includes("not authorized")||lower.includes("e-mail não autorizado")||lower.includes("email not authorized"))setError("Este e-mail ainda não foi autorizado pelo administrador da oficina.");else if(lower.includes("already registered")||lower.includes("already been registered")||lower.includes("já possui acesso"))setError("Este e-mail já possui acesso. Use a opção Entrar.");else setError(raw)}finally{setLoading(false)}}
 return <main className="compact-grid flex min-h-screen items-center justify-center bg-[#070707] px-4 py-10 text-white"><div className="w-full max-w-md"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-white/45 hover:text-[#FFC43D]"><ArrowLeft className="size-4"/>Voltar ao site</Link><div className="rounded-[2rem] border border-[#F0B323]/20 bg-[#111214]/95 p-6 shadow-2xl shadow-amber-500/5 sm:p-8"><div className="text-center"><img src={BRAND.iconUrl} alt="" className="mx-auto size-24 rounded-3xl object-contain"/><p className="mt-5 text-xs font-black uppercase tracking-[.25em] text-[#F0B323]">Sistema de gestão</p><h1 className="mt-2 text-3xl font-black">{mode==="login"?"Acesso administrativo":"Primeiro acesso"}</h1><p className="mt-2 text-sm leading-6 text-white/42">{mode==="login"?"Entre com o usuário autorizado da oficina.":"Use o e-mail cadastrado pelo administrador e crie sua senha."}</p></div>
 <div className="mt-6 grid grid-cols-2 rounded-2xl border border-white/8 bg-black/30 p-1"><button type="button" onClick={()=>switchMode("login")} className={`rounded-xl px-3 py-2.5 text-xs font-black ${mode==="login"?"bg-[#F0B323] text-black":"text-white/45"}`}>Entrar</button><button type="button" onClick={()=>switchMode("first")} className={`rounded-xl px-3 py-2.5 text-xs font-black ${mode==="first"?"bg-[#F0B323] text-black":"text-white/45"}`}>Primeiro acesso</button></div>
 <form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-white/45">E-mail</span><div className="relative"><Mail className="absolute left-3.5 top-1/2 size-5 -translate-y-1/2 text-[#F0B323]"/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/35 py-3.5 pl-11 pr-4 outline-none transition focus:border-[#F0B323]/60" placeholder="usuario@oficina.com.br"/></div></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-white/45">{mode==="login"?"Senha":"Crie sua senha"}</span><div className="relative"><LockKeyhole className="absolute left-3.5 top-1/2 size-5 -translate-y-1/2 text-[#F0B323]"/><input type={show?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==="first"?6:undefined} className="w-full rounded-2xl border border-white/10 bg-black/35 py-3.5 pl-11 pr-12 outline-none transition focus:border-[#F0B323]/60" placeholder={mode==="first"?"Mínimo de 6 caracteres":"Sua senha"}/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-white/40 hover:text-white">{show?<EyeOff className="size-5"/>:<Eye className="size-5"/>}</button></div></label>{mode==="first"&&<label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-white/45">Confirmar senha</span><div className="relative"><KeyRound className="absolute left-3.5 top-1/2 size-5 -translate-y-1/2 text-[#F0B323]"/><input type={show?"text":"password"} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={6} className="w-full rounded-2xl border border-white/10 bg-black/35 py-3.5 pl-11 pr-4 outline-none transition focus:border-[#F0B323]/60" placeholder="Repita a senha"/></div></label>}{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}{success&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{success}</div>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#F0B323] px-5 py-4 font-black text-black transition hover:bg-[#FFC43D] disabled:opacity-60">{loading?<Loader2 className="size-5 animate-spin"/>:mode==="first"?<KeyRound className="size-5"/>:<ShieldCheck className="size-5"/>}{loading?"Processando...":mode==="first"?"Criar meu acesso":"Entrar no painel"}</button></form></div><p className="mt-5 text-center text-xs text-white/28">{BRAND.name} • acesso protegido por autenticação</p></div></main>
}
