import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Eye, EyeOff, Loader2, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { BRAND } from "@/lib/brand";

export const Route = createFileRoute("/login")({ component: LoginPage });

function LoginPage() {
  const navigate = useNavigate();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{ void supabase.auth.getSession().then(({data})=>{ if(data.session) navigate({to:"/admin",replace:true}); }).catch(()=>{}); },[navigate]);
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError(null);try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;navigate({to:"/admin",replace:true});}catch(err){setError(err instanceof Error?err.message:"Não foi possível entrar.");}finally{setLoading(false)}}
  return <main className="compact-grid flex min-h-screen items-center justify-center bg-[#070707] px-4 py-10 text-white">
    <div className="w-full max-w-md"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-white/45 hover:text-[#FFC43D]"><ArrowLeft className="size-4"/> Voltar ao site</Link><div className="rounded-[2rem] border border-[#F0B323]/20 bg-[#111214]/95 p-6 shadow-2xl shadow-amber-500/5 sm:p-8"><div className="text-center"><img src={BRAND.iconUrl} alt="" className="mx-auto size-24 rounded-3xl object-contain"/><p className="mt-5 text-xs font-black uppercase tracking-[.25em] text-[#F0B323]">Sistema de gestão</p><h1 className="mt-2 text-3xl font-black">Acesso administrativo</h1><p className="mt-2 text-sm leading-6 text-white/42">Entre com o usuário autorizado da oficina.</p></div><form onSubmit={submit} className="mt-8 space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-white/45">E-mail</span><div className="relative"><Mail className="absolute left-3.5 top-1/2 size-5 -translate-y-1/2 text-[#F0B323]"/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/35 py-3.5 pl-11 pr-4 outline-none transition focus:border-[#F0B323]/60" placeholder="usuario@oficina.com.br"/></div></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-white/45">Senha</span><div className="relative"><LockKeyhole className="absolute left-3.5 top-1/2 size-5 -translate-y-1/2 text-[#F0B323]"/><input type={show?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/35 py-3.5 pl-11 pr-12 outline-none transition focus:border-[#F0B323]/60" placeholder="Sua senha"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-white/40 hover:text-white">{show?<EyeOff className="size-5"/>:<Eye className="size-5"/>}</button></div></label>{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#F0B323] px-5 py-4 font-black text-black transition hover:bg-[#FFC43D] disabled:opacity-60">{loading?<Loader2 className="size-5 animate-spin"/>:<ShieldCheck className="size-5"/>}{loading?"Entrando...":"Entrar no painel"}</button></form></div><p className="mt-5 text-center text-xs text-white/28">{BRAND.name} • acesso protegido por autenticação</p></div>
  </main>;
}
