import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, ShieldCheck, Wrench } from "lucide-react";
import { BRAND } from "@/lib/brand";

export const Route = createFileRoute("/servicos/$slug")({ component: ServicePage });
const catalog:Record<string,{title:string;description:string;items:string[];time:string}>={
  "troca-de-oleo":{title:"Troca de óleo e filtros",description:"Manutenção preventiva para preservar o motor, desempenho e vida útil do veículo.",items:["Óleo conforme especificação do fabricante","Filtro de óleo","Inspeção visual de vazamentos","Conferência de níveis"],time:"A partir de 45 min"},
  "freios":{title:"Sistema de freios",description:"Diagnóstico e manutenção dos principais componentes de frenagem.",items:["Pastilhas e discos","Fluido de freio","Pinças e componentes","Teste de segurança"],time:"A partir de 90 min"},
  "alinhamento-balanceamento":{title:"Alinhamento e balanceamento",description:"Geometria e equilíbrio para rodagem segura, confortável e desgaste uniforme.",items:["Alinhamento","Balanceamento","Inspeção de pneus","Conferência de suspensão"],time:"A partir de 60 min"},
  "pneus":{title:"Pneus",description:"Montagem, troca, inspeção e cuidados para segurança e desempenho.",items:["Troca e montagem","Calibragem","Inspeção de desgaste","Rodízio quando indicado"],time:"A partir de 45 min"},
  "mecanica-geral":{title:"Mecânica em geral",description:"Diagnóstico técnico e reparos mecânicos para diferentes sistemas do veículo.",items:["Diagnóstico","Manutenção preventiva","Reparos mecânicos","Teste final"],time:"Conforme diagnóstico"},
  "eletrica":{title:"Elétrica automotiva",description:"Análise e reparo de falhas elétricas e eletrônicas do veículo.",items:["Bateria e carga","Iluminação","Partida","Diagnóstico elétrico"],time:"Conforme diagnóstico"},
  "embreagem":{title:"Embreagem",description:"Diagnóstico e manutenção do conjunto de embreagem e acionamento.",items:["Kit de embreagem","Rolamentos","Acionamento","Teste de rodagem"],time:"Conforme diagnóstico"},
  "check-up":{title:"Revisão e check-up geral",description:"Inspeção preventiva dos principais sistemas antes que pequenos problemas se tornem grandes reparos.",items:["Fluidos e filtros","Freios e pneus","Suspensão e direção","Sistema elétrico"],time:"A partir de 120 min"},
};
function ServicePage(){const {slug}=Route.useParams();const service=catalog[slug]??{title:"Serviço automotivo",description:"Atendimento profissional com diagnóstico e acompanhamento.",items:["Avaliação técnica","Orçamento transparente","Execução registrada","Entrega com conferência"],time:"Conforme diagnóstico"};return <main className="min-h-screen bg-[#070707] text-white"><header className="border-b border-white/8"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/45 hover:text-[#FFC43D]"><ArrowLeft className="size-4"/> Início</Link><img src={BRAND.logoUrl} className="h-11 w-auto" alt={BRAND.name}/></div></header><section className="compact-grid"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#F0B323]/25 bg-[#F0B323]/8 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-[#FFC43D]"><Wrench className="size-4"/> Serviço automotivo</div><h1 className="mt-7 text-5xl font-black tracking-[-.04em] sm:text-6xl">{service.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">{service.description}</p><div className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white/[.04] px-4 py-3 text-sm font-bold text-white/65"><Clock3 className="size-4 text-[#F0B323]"/>{service.time}</div></div><div className="rounded-[2rem] border border-[#F0B323]/18 bg-[#111214] p-6 sm:p-8"><h2 className="text-xl font-black">O que avaliamos</h2><div className="mt-6 space-y-4">{service.items.map(item=><div key={item} className="flex items-center gap-3"><CheckCircle2 className="size-5 shrink-0 text-[#F0B323]"/><span className="text-white/72">{item}</span></div>)}</div><div className="mt-8 rounded-2xl border border-white/8 bg-black/25 p-5"><ShieldCheck className="size-6 text-[#F0B323]"/><p className="mt-3 font-black">Atendimento com transparência</p><p className="mt-2 text-sm leading-6 text-white/45">O serviço pode ser registrado em ordem de serviço e acompanhado pelo cliente.</p></div></div></div></section><div className="mx-auto max-w-6xl px-5 pb-20"><Link to="/" className="inline-flex items-center gap-2 rounded-2xl bg-[#F0B323] px-6 py-4 font-black text-black">Solicitar atendimento <ArrowRight className="size-5"/></Link></div></main>}
