import { useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Edit3, History, Loader2, Plus, Search, Trash2, X } from "lucide-react";
import { createCustomer, deleteCustomer, updateCustomer, useCustomerDirectory, useCustomerHistory, type CustomerInput } from "@/lib/customer-vehicle-operations";
import { money, STATUS_LABEL, type OrderStatus } from "@/lib/porfirid-queries";

const empty: CustomerInput = { name:"", phone:"", email:"", cpf_cnpj:"", cep:"", address:"", address_number:"", neighborhood:"", city:"", state:"", notes:"" };

export function CustomersManager({ userRole, onOpenOrder }: { userRole?: string; onOpenOrder: (id:string)=>void }) {
  const qc = useQueryClient();
  const { data = [], isLoading, error } = useCustomerDirectory();
  const [search,setSearch] = useState(""); const [editing,setEditing] = useState<any|null>(null); const [history,setHistory] = useState<string|null>(null); const [working,setWorking]=useState(false); const [msg,setMsg]=useState("");
  const canWrite = ["admin","atendimento"].includes(userRole ?? "");
  const rows = useMemo(()=>{ const t=search.toLowerCase().trim(); return !t?data:data.filter((c:any)=>[c.name,c.phone,c.email,c.cpf_cnpj,c.city].some(v=>String(v??"").toLowerCase().includes(t)));},[data,search]);
  const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["customer_directory"]}),qc.invalidateQueries({queryKey:["customers"]}),qc.invalidateQueries({queryKey:["dashboard"]})]);
  async function save(form:CustomerInput){setWorking(true);setMsg("");try{editing?.id?await updateCustomer(editing.id,form):await createCustomer(form);await refresh();setEditing(null);setMsg("Cliente salvo com sucesso.");}catch(e){setMsg(e instanceof Error?e.message:"Erro ao salvar cliente.");}finally{setWorking(false)}}
  async function remove(row:any){if(!confirm(`Excluir ${row.name}?`))return;setWorking(true);try{await deleteCustomer(row.id);await refresh();}catch(e){setMsg(e instanceof Error?e.message:"Erro ao excluir.");}finally{setWorking(false)}}
  if(isLoading)return <p className="p-6">Carregando clientes...</p>; if(error)return <p className="p-6 text-red-600">Não foi possível carregar os clientes.</p>;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-3.5 size-4 text-black/35"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente..."/></div>{canWrite&&<button className="goldButton" onClick={()=>setEditing({})}><Plus className="size-4"/> Novo cliente</button>}</div>
    {msg&&<div className="rounded-xl border border-black/10 bg-white p-3 text-sm">{msg}</div>}
    <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{rows.map((c:any)=><article key={c.id} className="rounded-2xl border border-black/8 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{c.name}</h3><p className="text-sm text-black/45">{c.phone}</p><p className="text-xs text-black/35">{c.email||"Sem e-mail"}</p></div><div className="rounded-xl bg-[#F0B323]/15 px-3 py-2 text-sm font-black">{c.vehicle_count} veículo(s)</div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-black/[.03] p-2"><b>{c.vehicle_count}</b><br/>Veículos</div><div className="rounded-xl bg-black/[.03] p-2"><b>{c.order_count}</b><br/>OS</div><div className="rounded-xl bg-black/[.03] p-2"><b>{c.appointment_count}</b><br/>Agenda</div></div><div className="mt-4 flex gap-2 border-t border-black/6 pt-4"><button className="secondaryButton" onClick={()=>setHistory(c.id)}><History className="size-4"/> Histórico</button>{canWrite&&<button className="secondaryButton" onClick={()=>setEditing(c)}><Edit3 className="size-4"/> Editar</button>}{userRole==="admin"&&c.vehicle_count===0&&c.order_count===0&&<button className="secondaryButton text-red-600" disabled={working} onClick={()=>void remove(c)}><Trash2 className="size-4"/></button>}</div></article>)}</div>
    {editing&&<CustomerModal customer={editing.id?editing:null} working={working} onClose={()=>setEditing(null)} onSave={save}/>} 
    {history&&<HistoryModal id={history} onClose={()=>setHistory(null)} onOpenOrder={(id)=>{setHistory(null);onOpenOrder(id)}}/>}
  </div>
}

function CustomerModal({customer,working,onClose,onSave}:{customer:any|null;working:boolean;onClose:()=>void;onSave:(f:CustomerInput)=>Promise<void>}){const [f,setF]=useState<CustomerInput>(customer?{...empty,...customer}:empty);const set=(k:keyof CustomerInput,v:any)=>setF(x=>({...x,[k]:v}));return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/65 p-4"><div className="mx-auto my-8 max-w-3xl rounded-3xl bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#B97900]">Clientes</p><h2 className="text-2xl font-black">{customer?"Editar cliente":"Novo cliente"}</h2></div><button onClick={onClose}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['name','Nome *'],['phone','Telefone / WhatsApp *'],['cpf_cnpj','CPF / CNPJ'],['email','E-mail'],['cep','CEP'],['address','Endereço'],['address_number','Número'],['neighborhood','Bairro'],['city','Cidade'],['state','UF']] as [keyof CustomerInput,string][]).map(([k,l])=><label key={k} className="text-sm font-bold">{l}<input className="field mt-1.5" value={String(f[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}</div><label className="mt-3 block text-sm font-bold">Observações<textarea className="field mt-1.5 min-h-24" value={String(f.notes??"")} onChange={e=>set('notes',e.target.value)}/></label><div className="mt-5 flex justify-end gap-2"><button className="secondaryButton" onClick={onClose}>Cancelar</button><button className="goldButton" disabled={working||!f.name.trim()||!f.phone.trim()} onClick={()=>void onSave(f)}>{working&&<Loader2 className="size-4 animate-spin"/>} Salvar</button></div></div></div>}

function HistoryModal({id,onClose,onOpenOrder}:{id:string;onClose:()=>void;onOpenOrder:(id:string)=>void}){const {data,isLoading}=useCustomerHistory(id);return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/65 p-4"><div className="mx-auto my-8 max-w-4xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">Ficha e histórico</h2><button onClick={onClose}><X/></button></div>{isLoading?<p className="mt-6">Carregando...</p>:data?<div className="mt-5 space-y-5"><div><h3 className="font-black">{(data.customer as any).name}</h3><p className="text-sm text-black/50">{(data.customer as any).phone}</p></div><div><h4 className="font-black">Veículos</h4><div className="mt-2 grid gap-2 sm:grid-cols-2">{data.vehicles.map((v:any)=><div key={v.id} className="rounded-xl bg-black/[.03] p-3">{v.brand} {v.model} • {v.plate}</div>)}</div></div><div><h4 className="font-black">Ordens de serviço</h4><div className="mt-2 space-y-2">{data.orders.map((o:any)=><button key={o.id} onClick={()=>onOpenOrder(o.id)} className="flex w-full justify-between rounded-xl border border-black/8 p-3 text-left"><span>OS #{o.order_number} • {STATUS_LABEL[o.status as OrderStatus]??o.status}</span><b>{money(Number(o.total??0))}</b></button>)}</div></div></div>:<p className="mt-5">Sem dados.</p>}</div></div>}
