import { useEffect, useMemo, useState } from "react";
import { Check, CheckCircle2, Copy, ExternalLink, Link2, MessageCircle, Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { BRAND } from "@/lib/brand";
import { useAppSettings } from "@/lib/app-settings";
import { STATUS_LABEL, type OrderStatus } from "@/lib/porfirid-queries";
const db=supabase as any;
const steps:OrderStatus[]=["recepcao","diagnostico","aguardando_aprovacao","em_execucao","finalizacao","pronto_entrega","entregue"];

export function CustomerTrackingPanel({order}:{order:any}){
 const {data:settings={}}=useAppSettings();
 const [tracking,setTracking]=useState<any>(null),[logs,setLogs]=useState<any[]>([]),[note,setNote]=useState(""),[status,setStatus]=useState<OrderStatus>(order.status),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const [t,l]=await Promise.all([db.from("work_order_tracking").select("*").eq("work_order_id",order.id).maybeSingle(),db.from("customer_communication_log").select("*").eq("work_order_id",order.id).order("created_at",{ascending:false}).limit(20)]);setTracking(t.data);setNote(t.data?.customer_note??"");setStatus((t.data?.status??order.status) as OrderStatus);setLogs(l.data??[])}useEffect(()=>{void load()},[order.id]);
 const customer=order.customers??{},vehicle=order.vehicles??{};const path=tracking?.access_token?`/acompanhar/${tracking.access_token}`:"";const url=path&&typeof window!=="undefined"?`${window.location.origin}${path}`:"";const currentIndex=steps.indexOf(status);
 const text=useMemo(()=>{const greeting=settings.whatsapp_greeting||`Olá, ${customer.name??"cliente"}! Aqui é da ${BRAND.name}.`;const configured=status==="pronto_entrega"?(settings.whatsapp_ready_message||""):(settings.whatsapp_tracking_message||"");return `${greeting}\n\n${configured?`${configured}\n\n`:""}Atualização da OS #${order.order_number}: ${STATUS_LABEL[status]??status}.\nVeículo: ${vehicle.brand??""} ${vehicle.model??""} • ${vehicle.plate??""}${note?`\n\nMensagem da oficina: ${note}`:""}\n\nAcompanhe em tempo real: ${url}`},[customer.name,note,order.order_number,settings.whatsapp_greeting,settings.whatsapp_ready_message,settings.whatsapp_tracking_message,status,url,vehicle.brand,vehicle.model,vehicle.plate]);
 async function save(){if(!tracking)return;setBusy(true);const {error}=await db.from("work_order_tracking").update({customer_note:note,status,updated_at:new Date().toISOString()}).eq("id",tracking.id);setBusy(false);setMessage(error?error.message:"Etapa e mensagem do acompanhamento atualizadas.");if(!error)await load()}
 async function copy(value:string,label:string){if(!value)return;await navigator.clipboard.writeText(value);setMessage(label)}
 async function sendWhatsApp(){if(!tracking)return;const phone=String(customer.phone??"").replace(/\D/g,"");if(!phone)return setMessage("Cliente sem WhatsApp cadastrado.");const normalized=phone.startsWith("55")?phone:`55${phone}`;setBusy(true);const {data:auth}=await supabase.auth.getUser();const {error}=await db.from("customer_communication_log").insert({work_order_id:order.id,channel:"whatsapp",direction:"outbound",message:text,sent_to:customer.phone??null,created_by:auth.user?.id??null});setBusy(false);if(error)return setMessage(error.message);window.open(`https://wa.me/${normalized}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");setMessage("Mensagem registrada no histórico e aberta no WhatsApp.");await load()}
 if(settings.tracking_enabled===false)return <div className="rounded-xl border border-dashed border-black/10 p-4 text-sm text-black/45">O acompanhamento público está desativado nas Configurações.</div>;
 if(!tracking)return <div className="rounded-xl border border-dashed border-black/10 p-4 text-sm text-black/45">O link público será criado automaticamente quando a OS for registrada.</div>;
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><div className="rounded-lg bg-[#F0B323]/15 p-2 text-[#8A5F00]"><Link2 className="size-4"/></div><p className="font-black">Acompanhamento e comunicação</p></div><p className="mt-2 text-xs leading-relaxed text-black/48">Escolha a etapa mostrada ao cliente, escreva um recado e envie manualmente pelo WhatsApp.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[11px] font-black text-emerald-700">Link ativo</span></div>
 <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{steps.map((step,index)=>{const active=status===step,done=index<currentIndex;return <button key={step} type="button" onClick={()=>setStatus(step)} className={`rounded-2xl border p-3 text-left ${active?"border-[#F0B323] bg-[#F0B323]/8":done?"border-emerald-200 bg-emerald-50":"border-black/7 bg-black/[.015]"}`}><div className={`flex size-7 items-center justify-center rounded-full text-xs font-black ${active?"bg-[#F0B323] text-black":done?"bg-emerald-600 text-white":"bg-black/6 text-black/35"}`}>{done?<Check className="size-4"/>:index+1}</div><p className="mt-2 text-xs font-black">{STATUS_LABEL[step]??step}</p></button>})}</div>
 <div className="rounded-xl bg-black/[.025] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-black/35">Link público</p><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input readOnly value={url} className="field flex-1"/><button onClick={()=>void copy(url,"Link copiado.")} className="secondaryButton"><Copy className="size-4"/>Copiar</button><a href={path} target="_blank" rel="noreferrer" className="secondaryButton"><ExternalLink className="size-4"/>Visualizar</a></div></div>
 <label className="block text-sm font-bold">Recado visível ao cliente<textarea rows={4} className="field mt-2 resize-y" value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: As peças chegaram e a montagem será concluída ainda hoje."/></label>
 <div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4"><p className="text-xs font-black uppercase tracking-wider text-emerald-800">Prévia da mensagem</p><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-white p-4 font-sans text-xs leading-5 text-black/65">{text}</pre><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void save()} className="secondaryButton"><Save className="size-4"/>Salvar atualização</button><button onClick={()=>void copy(text,"Mensagem copiada.")} className="secondaryButton"><Copy className="size-4"/>Copiar mensagem</button><button disabled={busy} onClick={()=>void sendWhatsApp()} className="goldButton"><MessageCircle className="size-4"/>Abrir WhatsApp</button></div></div>
 {message&&<p className="rounded-xl bg-[#F0B323]/10 p-3 text-xs font-bold text-[#6F4B00]">{message}</p>}
 <div><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-black/35">Histórico de comunicação</p>{logs.length>0&&<span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-3.5"/>{logs.length} registro(s)</span>}</div><div className="mt-2 space-y-2">{logs.map(x=><div key={x.id} className="rounded-xl bg-black/[.025] p-3 text-xs"><div className="flex justify-between gap-3"><b>{x.channel} • {x.sent_to??"cliente"}</b><span className="text-black/35">{new Date(x.created_at).toLocaleString("pt-BR")}</span></div><p className="mt-2 whitespace-pre-wrap text-black/60">{x.message}</p></div>)}{logs.length===0&&<p className="text-sm text-black/40">Nenhuma comunicação registrada.</p>}</div></div></div>;
}
