import { useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Edit3, History, Loader2, Mail, MapPin, Phone, Plus, Search, Trash2, UserRound, X } from "lucide-react";
import { createCustomer, deleteCustomer, updateCustomer, useCustomerDirectory, useCustomerHistory, type CustomerInput } from "@/lib/customer-vehicle-operations";
import { money, STATUS_LABEL, type OrderStatus } from "@/lib/porfirid-queries";

const GOLD = "#F0B323";
const emptyCustomer: CustomerInput = { name: "", cpf_cnpj: "", phone: "", email: "", cep: "", address: "", address_number: "", neighborhood: "", city: "", state: "", notes: "" };

export function CustomersManager({ userRole, onOpenOrder }: { userRole?: string | undefined; onOpenOrder: (id: string) => void }) {
  const queryClient = useQueryClient();
  const { data = [], isLoading, error } = useCustomerDirectory();
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<any | null>(null); const [showForm, setShowForm] = useState(false); const [historyId, setHistoryId] = useState<string | null>(null); const [working, setWorking] = useState(false); const [message, setMessage] = useState<string | null>(null); const [actionError, setActionError] = useState<string | null>(null);
  const canWrite = ["admin", "atendimento"].includes(userRole ?? "");
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return data; return data.filter((customer: any) => [customer.name, customer.phone, customer.cpf_cnpj, customer.email, customer.city].filter(Boolean).some((value) => String(value).toLowerCase().includes(term))); }, [data, search]);
  async function refresh() { await Promise.all([queryClient.invalidateQueries({ queryKey: ["customer_directory"] }), queryClient.invalidateQueries({ queryKey: ["customers"] }), queryClient.invalidateQueries({ queryKey: ["appointment_customers"] }), queryClient.invalidateQueries({ queryKey: ["dashboard"] })]); }
  async function save(input: CustomerInput) { setWorking(true); setActionError(null); try { if (editing?.id) await updateCustomer(editing.id, input); else await createCustomer(input); await refresh(); setShowForm(false); setEditing(null); setMessage(editing?.id ? "Cliente atualizado." : "Cliente cadastrado."); } catch (err) { setActionError(err instanceof Error ? err.message : "Não foi possível salvar o cliente."); } finally { setWorking(false); } }
  async function remove(customer: any) { if (!window.confirm(`Excluir ${customer.name}? Esta ação só será permitida se não houver histórico vinculado.`)) return; setWorking(true); setActionError(null); try { await deleteCustomer(customer.id); await refresh(); setMessage("Cliente excluído."); } catch (err) { setActionError(err instanceof Error ? err.message : "Não foi possível excluir o cliente."); } finally { setWorking(false); } }
  if (isLoading) return <Loading />; if (error) return <Notice error text="Não foi possível carregar os clientes." />;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-black/35" /><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar por nome, telefone, CPF/CNPJ, e-mail ou cidade..." className="w-full rounded-xl border border-black/10 bg-white py-3 pl-10 pr-3 text-sm outline-none focus:border-[#F0B323]" /></div>{canWrite && <button onClick={()=>{setEditing(null);setShowForm(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#F0B323] px-4 py-3 text-sm font-black text-black hover:bg-[#FFC43D]"><Plus className="size-4"/> Novo cliente</button>}</div>
    {(message||actionError)&&<Notice error={Boolean(actionError)} text={actionError??message??""}/>} 
    {filtered.length===0?<div className="rounded-2xl border border-dashed border-black/12 bg-white p-10 text-center"><UserRound className="mx-auto size-9 text-[#F0B323]"/><p className="mt-3 font-black">{search?"Nenhum cliente encontrado":"Nenhum cliente cadastrado"}</p></div>:<div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{filtered.map((customer:any)=><article key={customer.id} className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#F0B323]/10 font-black text-[#B97900]">{initials(customer.name)}</div><div className="min-w-0 flex-1"><h3 className="truncate font-black">{customer.name}</h3><p className="mt-1 text-xs text-black/42">{customer.cpf_cnpj||"CPF/CNPJ não informado"}</p></div></div><div className="mt-4 space-y-2 text-sm text-black/58"><Row icon={Phone} value={customer.phone}/>{customer.email&&<Row icon={Mail} value={customer.email}/>}<Row icon={MapPin} value={[customer.city,customer.state].filter(Boolean).join(" / ")||"Endereço não informado"}/></div><div className="mt-4 grid grid-cols-3 gap-2"><Stat label="Veículos" value={customer.vehicle_count}/><Stat label="OS" value={customer.order_count}/><Stat label="Agenda" value={customer.appointment_count}/></div><div className="mt-4 flex flex-wrap gap-2 border-t border-black/6 pt-4"><button onClick={()=>setHistoryId(customer.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-black/10 px-3 py-2 text-xs font-black hover:border-[#F0B323]/50"><History className="size-3.5"/> Ficha e histórico</button>{canWrite&&<button onClick={()=>{setEditing(customer);setShowForm(true)}} className="inline-flex items-center gap-1.5 rounded-lg border border-black/10 px-3 py-2 text-xs font-bold"><Edit3 className="size-3.5"/> Editar</button>}{userRole==="admin"&&customer.vehicle_count===0&&customer.order_count===0&&customer.appointment_count===0&&<button disabled={working} onClick={()=>void remove(customer)} className="inline-flex items-center gap-1.5 rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><Trash2 className="size-3.5"/> Excluir</button>}</div></article>)}</div>}
    {showForm&&<CustomerForm customer={editing} working={working} error={actionError} onClose={()=>{setShowForm(false);setEditing(null);setActionError(null)}} onSave={save}/>} {historyId&&<CustomerHistory customerId={historyId} onClose={()=>setHistoryId(null)} onOpenOrder={(id)=>{setHistoryId(null);onOpenOrder(id)}}/>}
  </div>;
}

function CustomerForm({customer,working,error,onClose,onSave}:{customer:any|null;working:boolean;error:string|null;onClose:()=>void;onSave:(input:CustomerInput)=>Promise<void>}){const [form,setForm]=useState<CustomerInput>(customer?{name:customer.name??"",cpf_cnpj:customer.cpf_cnpj??"",phone:customer.phone??"",email:customer.email??"",cep:customer.cep??"",address:customer.address??"",address_number:customer.address_number??"",neighborhood:customer.neighborhood??"",city:customer.city??"",state:customer.state??"",notes:customer.notes??""}:emptyCustomer);function set<K extends keyof CustomerInput>(key:K,value:CustomerInput[K]){setForm(c=>({...c,[key]:value}))}return <Overlay onClose={onClose}><div className="flex items-center justify-between border-b border-black/7 pb-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#B97900]">Clientes</p><h2 className="mt-1 text-xl font-black">{customer?"Editar cliente":"Novo cliente"}</h2></div><button onClick={onClose} className="rounded-xl border border-black/10 p-2"><X className="size-5"/></button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Nome *" value={form.name} onChange={v=>set("name",v)}/><Field label="WhatsApp / telefone *" value={form.phone} onChange={v=>set("phone",v)}/><Field label="CPF / CNPJ" value={String(form.cpf_cnpj??"")} onChange={v=>set("cpf_cnpj",v)}/><Field label="E-mail" value={String(form.email??"")} onChange={v=>set("email",v)} type="email"/><Field label="CEP" value={String(form.cep??"")} onChange={v=>set("cep",v)}/><Field label="Endereço" value={String(form.address??"")} onChange={v=>set("address",v)}/><Field label="Número" value={String(form.address_number??"")} onChange={v=>set("address_number",v)}/><Field label="Bairro" value={String(form.neighborhood??"")} onChange={v=>set("neighborhood",v)}/><Field label="Cidade" value={String(form.city??"")} onChange={v=>set("city",v)}/><Field label="UF" value={String(form.state??"")} onChange={v=>set("state",v.toUpperCase().slice(0,2))}/></div><label className="mt-3 block text-sm font-semibold"><span>Observações</span><textarea rows={4} value={String(form.notes??"")} onChange={e=>set("notes",e.target.value)} className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3 text-sm font-normal outline-none focus:border-[#F0B323]"/></label>{error&&<Notice error text={error}/>}<div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-black/10 px-4 py-2.5 text-sm font-bold">Cancelar</button><button disabled={working||!form.name.trim()||!form.phone.trim()} onClick={()=>void onSave(form)} className="inline-flex items-center gap-2 rounded-xl bg-[#F0B323] px-5 py-2.5 text-sm font-black text-black disabled:opacity-45">{working&&<Loader2 className="size-4 animate-spin"/>} Salvar cliente</button></div></Overlay>}
function CustomerHistory({customerId,onClose,onOpenOrder}:{customerId:string;onClose:()=>void;onOpenOrder:(id:string)=>void}){const {data,isLoading,error}=useCustomerHistory(customerId);if(isLoading)return <Overlay onClose={onClose}><Loading/></Overlay>;if(error||!data)return <Overlay onClose={onClose}><Notice error text="Não foi possível carregar o histórico."/></Overlay>;const c:any=data.customer;return <Overlay onClose={onClose}><div className="flex items-start justify-between border-b border-black/7 pb-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#B97900]">Ficha do cliente</p><h2 className="mt-1 text-2xl font-black">{c.name}</h2><p className="mt-1 text-sm text-black/45">{c.phone} {c.email?`• ${c.email}`:""}</p></div><button onClick={onClose} className="rounded-xl border border-black/10 p-2"><X className="size-5"/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Veículos" value={data.vehicles.length}/><Stat label="Ordens de serviço" value={data.orders.length}/><Stat label="Agendamentos" value={data.appointments.length}/></div><section className="mt-6"><h3 className="font-black">Histórico de OS</h3><div className="mt-3 space-y-2">{data.orders.map((order:any)=><button key={order.id} onClick={()=>onOpenOrder(order.id)} className="flex w-full items-center gap-2 rounded-xl border border-black/7 p-3 text-left"><span className="font-black text-[#B97900]">OS #{order.order_number}</span><span className="flex-1 text-xs text-black/50">{STATUS_LABEL[order.status as OrderStatus]??order.status}</span><span className="text-sm font-black">{money(Number(order.total??0))}</span></button>)}</div></section></Overlay>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm font-semibold"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-3 text-sm font-normal outline-none focus:border-[#F0B323]"/></label>}
function Row({icon:Icon,value}:{icon:typeof Phone;value:string}){return <div className="flex items-center gap-2"><Icon className="size-4 shrink-0 text-[#B97900]"/><span className="truncate">{value}</span></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-black/[0.025] px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function Notice({error=false,text}:{error?:boolean;text:string}){return <p className={`mt-3 rounded-xl px-4 py-3 text-sm font-semibold ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{text}</p>}
function Overlay({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-[75] overflow-y-auto bg-black/65 p-3 backdrop-blur-sm sm:p-6"><button className="fixed inset-0" onClick={onClose}/><div className="relative mx-auto max-w-5xl rounded-3xl bg-white p-5 shadow-2xl sm:p-7">{children}</div></div>}
function Loading(){return <div className="flex min-h-40 items-center justify-center"><Loader2 className="size-7 animate-spin text-[#B97900]"/></div>}
function initials(name:string){return String(name).split(/\s+/).filter(Boolean).map(p=>p[0]).slice(0,2).join("").toUpperCase()||"CL"}
