import { useMemo, useState } from "react";
import { Loader2, PackagePlus, Plus, Trash2, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { money } from "@/lib/porfirid-queries";
const db=supabase as any;
export function FrontdeskWorkOrderItemsPanel({workOrderId,parts,services,locked=false,onChanged}:{workOrderId:string;parts:any[];services:any[];locked?:boolean;onChanged:()=>Promise<void>}){
 const [inventory,setInventory]=useState<any[]|null>(null),[selectedId,setSelectedId]=useState(""),[quantity,setQuantity]=useState(1),[unitPrice,setUnitPrice]=useState(0),[manualPart,setManualPart]=useState({description:"",quantity:1,unitPrice:0}),[labor,setLabor]=useState({description:"",quantity:1,unitPrice:0}),[working,setWorking]=useState(false),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
 async function ensureInventory(){if(inventory)return inventory;const {data,error}=await db.rpc("get_frontdesk_inventory");if(error)throw error;const rows=data??[];setInventory(rows);return rows}
 const available=useMemo(()=>inventory?.filter((i:any)=>i.active&&Number(i.quantity)>0)??[],[inventory]);const selected=available.find((i:any)=>i.id===selectedId)??null;const manualLabor=services.filter((s:any)=>!s.service_id);
 async function run(action:()=>Promise<any>,success:string){setWorking(true);setMessage(null);try{await action();await onChanged();setMessage({type:"success",text:success})}catch(e:any){setMessage({type:"error",text:e?.message??"Não foi possível concluir a ação."})}finally{setWorking(false)}}
 async function openInventory(){try{const rows=await ensureInventory();if(!selectedId&&rows.length){const first=rows.find((i:any)=>i.active&&Number(i.quantity)>0);if(first){setSelectedId(first.id);setUnitPrice(Number(first.sale_price??0))}}}catch(e:any){setMessage({type:"error",text:e?.message??"Não foi possível carregar o estoque."})}}
 return <div className="space-y-6">{message&&<p className={`rounded-xl px-3 py-2.5 text-sm font-semibold ${message.type==="error"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{message.text}</p>}
 {!locked&&<section className="rounded-2xl border border-[#F0B323]/20 bg-[#F0B323]/[0.035] p-4"><p className="font-black">Adicionar peça manualmente</p><div className="mt-3 grid gap-3 md:grid-cols-[1.7fr_.45fr_.75fr_auto] md:items-end"><Field label="Descrição"><input className="field" value={manualPart.description} onChange={e=>setManualPart({...manualPart,description:e.target.value})}/></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" className="field" value={manualPart.quantity} onChange={e=>setManualPart({...manualPart,quantity:Number(e.target.value)})}/></Field><Field label="Preço de venda"><input type="number" min="0" step="0.01" className="field" value={manualPart.unitPrice} onChange={e=>setManualPart({...manualPart,unitPrice:Number(e.target.value)})}/></Field><button disabled={working||!manualPart.description.trim()} onClick={()=>void run(async()=>{const {error}=await db.rpc("frontdesk_add_manual_part",{p_work_order_id:workOrderId,p_description:manualPart.description,p_quantity:manualPart.quantity,p_unit_price:manualPart.unitPrice});if(error)throw error;setManualPart({description:"",quantity:1,unitPrice:0})},"Peça adicionada à OS.")} className="goldButton"><Plus className="size-4"/>Adicionar</button></div></section>}
 {!locked&&<section className="rounded-2xl border border-black/6 bg-[#fafafa] p-4"><div className="flex items-center justify-between gap-3"><p className="font-black">Peça do estoque</p>{inventory===null&&<button onClick={()=>void openInventory()} className="secondaryButton"><PackagePlus className="size-4"/>Carregar estoque</button>}</div>{inventory!==null&&<div className="mt-3 grid gap-3 md:grid-cols-[1.7fr_.45fr_.75fr_auto] md:items-end"><Field label="Peça"><select className="field" value={selectedId} onChange={e=>{const id=e.target.value;setSelectedId(id);const item=available.find((x:any)=>x.id===id);setUnitPrice(Number(item?.sale_price??0))}}><option value="">Selecione...</option>{available.map((i:any)=><option key={i.id} value={i.id}>{i.name} • {Number(i.quantity)} {i.unit} disponíveis</option>)}</select></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" className="field" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></Field><Field label="Preço de venda"><input type="number" min="0" step="0.01" className="field" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></Field><button disabled={working||!selectedId} onClick={()=>void run(async()=>{const {error}=await db.rpc("add_inventory_part_to_work_order",{p_work_order_id:workOrderId,p_inventory_item_id:selectedId,p_quantity:quantity,p_unit_price:unitPrice});if(error)throw error;setSelectedId("");setQuantity(1);setUnitPrice(0);setInventory(null)},"Peça lançada e baixada do estoque.")} className="goldButton">{working?<Loader2 className="size-4 animate-spin"/>:<PackagePlus className="size-4"/>}Lançar</button></div>}</section>}
 <section><p className="mb-3 font-black">Peças da OS</p>{parts.length===0?<p className="text-sm text-black/45">Nenhuma peça lançada.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-black/7 text-[11px] uppercase text-black/35"><th className="pb-3">Peça</th><th>Qtd.</th><th>Preço unit.</th><th>Total</th><th>Ação</th></tr></thead><tbody>{parts.map((p:any)=><tr key={p.id} className="border-b border-black/5"><td className="py-3 font-bold">{p.description}</td><td>{Number(p.quantity)}</td><td>{money(Number(p.unit_price??0))}</td><td className="font-black">{money(Number(p.quantity)*Number(p.unit_price??0))}</td><td>{locked?<span className="text-xs text-black/35">Fechado</span>:<button disabled={working} onClick={()=>void run(async()=>{const {error}=await db.rpc("frontdesk_remove_part",{p_part_id:p.id});if(error)throw error},"Peça removida.")} className="rounded-lg border border-black/10 p-2 text-red-700"><Trash2 className="size-3.5"/></button>}</td></tr>)}</tbody></table></div>}</section>
 <section className="border-t border-black/7 pt-5"><div className="flex items-center gap-2"><Wrench className="size-4 text-[#B97900]"/><p className="font-black">Mão de obra manual</p></div>{!locked&&<div className="mt-3 grid gap-3 rounded-2xl bg-[#fafafa] p-4 md:grid-cols-[1.7fr_.45fr_.75fr_auto] md:items-end"><Field label="Descrição"><input className="field" value={labor.description} onChange={e=>setLabor({...labor,description:e.target.value})}/></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" className="field" value={labor.quantity} onChange={e=>setLabor({...labor,quantity:Number(e.target.value)})}/></Field><Field label="Preço de venda"><input type="number" min="0" step="0.01" className="field" value={labor.unitPrice} onChange={e=>setLabor({...labor,unitPrice:Number(e.target.value)})}/></Field><button disabled={working||!labor.description.trim()} onClick={()=>void run(async()=>{const {error}=await db.rpc("frontdesk_add_manual_labor",{p_work_order_id:workOrderId,p_description:labor.description,p_quantity:labor.quantity,p_unit_price:labor.unitPrice});if(error)throw error;setLabor({description:"",quantity:1,unitPrice:0})},"Mão de obra adicionada.")} className="goldButton"><Plus className="size-4"/>Adicionar</button></div>}{manualLabor.length>0&&<div className="mt-3 space-y-2">{manualLabor.map((s:any)=><div key={s.id} className="flex items-center gap-3 rounded-xl border border-black/6 p-3"><div className="flex-1"><p className="font-bold">{s.description}</p><p className="text-xs text-black/40">{Number(s.quantity)} × {money(Number(s.unit_price??0))}</p></div><strong>{money(Number(s.quantity)*Number(s.unit_price??0))}</strong>{!locked&&<button disabled={working} onClick={()=>void run(async()=>{const {error}=await db.rpc("frontdesk_remove_labor",{p_service_id:s.id});if(error)throw error},"Mão de obra removida.")} className="rounded-lg border border-black/10 p-2 text-red-700"><Trash2 className="size-3.5"/></button>}</div>)}</div>}</section>
 </div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5 text-sm font-semibold"><span>{label}</span>{children}</label>}
