import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, CheckCircle2, Loader2, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { ManualItemsEditor } from "@/components/admin/ManualItemsEditor";
import { money, useCustomers } from "@/lib/porfirid-queries";
import { createWorkOrderIntakeV2, type ManualLineItem } from "@/lib/work-order-intake-v2";

const db = supabase as any;
type Props = { onCreated?: (result: { id: string; orderNumber: number; total: number }) => void };
type ChecklistKey = "mileage_checked"|"fuel_checked"|"front_checked"|"rear_checked"|"left_side_checked"|"right_side_checked"|"wheels_checked"|"tires_checked"|"lights_checked"|"windshield_checked"|"interior_checked"|"dashboard_checked"|"spare_tire_checked"|"tools_checked"|"belongings_checked";
const checklistItems:Array<[ChecklistKey,string]>=[["mileage_checked","Quilometragem conferida"],["fuel_checked","Nível de combustível"],["front_checked","Frente do veículo"],["rear_checked","Traseira do veículo"],["left_side_checked","Lateral esquerda"],["right_side_checked","Lateral direita"],["wheels_checked","Rodas"],["tires_checked","Pneus"],["lights_checked","Iluminação"],["windshield_checked","Para-brisa"],["interior_checked","Interior"],["dashboard_checked","Painel / alertas"],["spare_tire_checked","Estepe"],["tools_checked","Ferramentas / macaco"],["belongings_checked","Pertences no veículo"]];
const blankLine=():ManualLineItem=>({description:"",quantity:1,unit_price:0});
const emptyChecklist=()=>Object.fromEntries(checklistItems.map(([key])=>[key,false])) as Record<ChecklistKey,boolean>;

export function NewWorkOrderFlow({onCreated}:Props){
  const queryClient=useQueryClient();
  const {data:customers=[]}=useCustomers();
  const {data:allVehicles=[]}=useQuery({queryKey:["vehicle_options"],queryFn:async()=>{const {data,error}=await db.from("vehicles").select("id,customer_id,plate,brand,model,version,year,current_mileage").order("created_at",{ascending:false});if(error)throw error;return data??[];}});
  const [customerMode,setCustomerMode]=useState<"new"|"existing">("existing"); const [customerId,setCustomerId]=useState("");
  const [vehicleMode,setVehicleMode]=useState<"new"|"existing">("new"); const [vehicleId,setVehicleId]=useState("");
  const [parts,setParts]=useState<ManualLineItem[]>([blankLine()]); const [labor,setLabor]=useState<ManualLineItem[]>([blankLine()]);
  const [photos,setPhotos]=useState<File[]>([]); const [checklist,setChecklist]=useState<Record<ChecklistKey,boolean>>(emptyChecklist());
  const [discount,setDiscount]=useState(0); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<any>(null);
  const customerVehicles=useMemo(()=>allVehicles.filter((v:any)=>v.customer_id===customerId),[allVehicles,customerId]);
  const total=Math.max([...parts,...labor].reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unit_price||0),0)-Number(discount||0),0);
  function chooseCustomer(id:string){setCustomerId(id);setVehicleId("");const has=allVehicles.some((v:any)=>v.customer_id===id);setVehicleMode(has?"existing":"new");}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setError(null);const cleanParts=parts.filter(i=>i.description.trim());const cleanLabor=labor.filter(i=>i.description.trim());if(!cleanParts.length&&!cleanLabor.length)return setError("Informe pelo menos uma peça ou mão de obra.");if(customerMode==="existing"&&!customerId)return setError("Selecione o cliente.");if(vehicleMode==="existing"&&!vehicleId)return setError("Selecione o veículo.");setSubmitting(true);try{const result=await createWorkOrderIntakeV2({customer:customerMode==="existing"?{id:customerId}:{name:String(form.get("customer_name")||"").trim(),phone:String(form.get("customer_phone")||"").trim(),cpf_cnpj:String(form.get("cpf_cnpj")||"").trim(),email:String(form.get("customer_email")||"").trim(),city:String(form.get("city")||"").trim(),state:String(form.get("state")||"").trim().toUpperCase(),notes:String(form.get("customer_notes")||"").trim()},vehicle:vehicleMode==="existing"?{id:vehicleId,current_mileage:String(form.get("mileage_in")||"").replace(/\D/g,"")}:{plate:String(form.get("plate")||"").trim().toUpperCase(),brand:String(form.get("brand")||"").trim(),model:String(form.get("model")||"").trim(),version:String(form.get("version")||"").trim(),year:String(form.get("year")||"").trim(),model_year:String(form.get("model_year")||"").trim(),color:String(form.get("color")||"").trim(),fuel:String(form.get("vehicle_fuel")||"").trim(),current_mileage:String(form.get("mileage_in")||"").replace(/\D/g,"")},order:{mileage_in:String(form.get("mileage_in")||"").replace(/\D/g,""),fuel_level:String(form.get("fuel_level")||"").trim(),promised_at:String(form.get("promised_at")||"").trim(),customer_report:String(form.get("customer_report")||"").trim(),internal_notes:String(form.get("internal_notes")||"").trim(),discount:String(discount||0)},checklist:{...checklist,damage_notes:String(form.get("damage_notes")||"").trim()},parts:cleanParts,labor:cleanLabor,photos});setSuccess(result);await Promise.all([queryClient.invalidateQueries({queryKey:["dashboard"]}),queryClient.invalidateQueries({queryKey:["customers"]}),queryClient.invalidateQueries({queryKey:["vehicles"]}),queryClient.invalidateQueries({queryKey:["work_orders"]}),queryClient.invalidateQueries({queryKey:["inventory_items"]})]);onCreated?.(result);}catch(err){setError(err instanceof Error?err.message:"Não foi possível criar a OS.");}finally{setSubmitting(false)}}
  if(success)return <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex gap-4"><div className="rounded-2xl bg-emerald-600 p-3 text-white"><CheckCircle2 className="size-6"/></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">OS criada</p><h3 className="mt-1 text-2xl font-black">OS #{success.orderNumber}</h3><p className="mt-2 text-sm text-black/55">Total inicial: <strong>{money(success.total)}</strong>.</p>{success.photoWarnings?.length>0&&<p className="mt-2 text-xs font-semibold text-amber-700">{success.photoWarnings.length} foto(s) precisam ser reenviadas.</p>}<button type="button" onClick={()=>setSuccess(null)} className="goldButton mt-4">Abrir outra OS</button></div></div></div>;
  return <form onSubmit={submit} className="overflow-hidden rounded-3xl border border-[#F0B323]/25 bg-white shadow-sm"><div className="bg-[#111214] px-5 py-5 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Nova ordem de serviço</p><h3 className="mt-1 text-xl font-black">Entrada completa do veículo</h3><p className="mt-1 text-xs text-white/45">Cliente, veículo, peças, mão de obra, checklist e fotos em um único fluxo.</p></div><div className="space-y-7 p-5 sm:p-6">
    <Section title="1. Cliente"><ModeSwitch value={customerMode} onChange={(v)=>{setCustomerMode(v);setCustomerId("");setVehicleId("");setVehicleMode("new")}} existingLabel={`Cliente existente (${customers.length})`} newLabel="Novo cliente"/><div className="mt-3">{customerMode==="existing"?<Select name="customer" value={customerId} onChange={(e)=>chooseCustomer(e.target.value)}><option value="">Selecione...</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</Select>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field name="customer_name" label="Nome *"/><Field name="customer_phone" label="WhatsApp *"/><Field name="cpf_cnpj" label="CPF / CNPJ"/><Field name="customer_email" label="E-mail" type="email"/><Field name="city" label="Cidade"/><Field name="state" label="UF"/></div>}</div></Section>
    <Section title="2. Veículo">{customerMode==="existing"&&customerId&&<ModeSwitch value={vehicleMode} onChange={(v)=>{setVehicleMode(v);setVehicleId("")}} existingLabel={`Veículo existente (${customerVehicles.length})`} newLabel="Novo veículo"/>}<div className="mt-3">{vehicleMode==="existing"&&customerMode==="existing"?<Select name="vehicle" value={vehicleId} onChange={(e)=>setVehicleId(e.target.value)}><option value="">Selecione...</option>{customerVehicles.map((v:any)=><option key={v.id} value={v.id}>{v.brand} {v.model} • {v.plate}</option>)}</Select>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field name="plate" label="Placa *"/><Field name="brand" label="Marca *"/><Field name="model" label="Modelo *"/><Field name="version" label="Versão"/><Field name="year" label="Ano" type="number"/><Field name="model_year" label="Ano modelo" type="number"/><Field name="color" label="Cor"/><Field name="vehicle_fuel" label="Combustível"/></div>}</div></Section>
    <Section title="3. Peças"><ManualItemsEditor title="Peças utilizadas" subtitle="Selecione do estoque ou adicione manualmente." singular="peça" items={parts} onChange={setParts}/></Section>
    <Section title="4. Mão de obra"><ManualItemsEditor title="Mão de obra / serviços" subtitle="Informe descrição, quantidade e valor." singular="mão de obra" items={labor} onChange={setLabor}/></Section>
    <Section title="5. Entrada, checklist e fotos"><div className="grid gap-3 md:grid-cols-3"><Field name="mileage_in" label="Quilometragem"/><Field name="fuel_level" label="Nível de combustível" placeholder="Ex.: 1/2 tanque"/><Field name="promised_at" label="Previsão de entrega" type="datetime-local"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{checklistItems.map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl bg-[#fafafa] px-3 py-2.5 text-xs font-semibold"><input type="checkbox" checked={checklist[key]} onChange={(e)=>setChecklist(c=>({...c,[key]:e.target.checked}))} className="accent-[#F0B323]"/>{label}</label>)}</div><TextArea name="damage_notes" label="Avarias / observações de entrada"/><div className="mt-4"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-black/10 px-4 py-3 text-sm font-black"><Camera className="size-4 text-[#9B6600]"/>Anexar fotos<input type="file" accept="image/*" multiple className="hidden" onChange={(e)=>setPhotos(c=>[...c,...Array.from(e.target.files??[])])}/></label>{photos.length>0&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{photos.map((f,i)=><PhotoPreview key={`${f.name}-${i}`} file={f} onRemove={()=>setPhotos(c=>c.filter((_,x)=>x!==i))}/>)}</div>}</div></Section>
    <Section title="6. Relato, observações e total"><div className="grid gap-3 lg:grid-cols-2"><TextArea name="customer_report" label="Relato do cliente"/><TextArea name="internal_notes" label="Observações internas"/></div><div className="mt-4 grid items-end gap-3 sm:grid-cols-[1fr_auto]"><label className="text-sm font-bold">Desconto<input type="number" min="0" step="0.01" value={discount} onChange={(e)=>setDiscount(Number(e.target.value))} className="field mt-2"/></label><div className="rounded-2xl bg-[#111214] px-6 py-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Total estimado</p><p className="mt-1 text-2xl font-black text-[#FFC43D]">{money(total)}</p></div></div></Section>
    {error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<button disabled={submitting} className="goldButton w-full justify-center py-4 text-base">{submitting?<><Loader2 className="size-5 animate-spin"/>Salvando OS...</>:"Criar ordem de serviço completa"}</button>
  </div></form>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h4 className="mb-3 text-sm font-black uppercase tracking-[.14em] text-[#8A5F00]">{title}</h4>{children}</section>}
function ModeSwitch({value,onChange,existingLabel,newLabel}:{value:"new"|"existing";onChange:(v:"new"|"existing")=>void;existingLabel:string;newLabel:string}){return <div className="inline-flex rounded-xl bg-black/[.04] p-1"><button type="button" onClick={()=>onChange("existing")} className={`rounded-lg px-3 py-2 text-xs font-black ${value==="existing"?"bg-[#F0B323] text-black":"text-black/50"}`}>{existingLabel}</button><button type="button" onClick={()=>onChange("new")} className={`rounded-lg px-3 py-2 text-xs font-black ${value==="new"?"bg-[#F0B323] text-black":"text-black/50"}`}>{newLabel}</button></div>}
function Field({name,label,type="text",placeholder}:{name:string;label:string;type?:string;placeholder?:string}){return <label className="text-sm font-bold"><span>{label}</span><input name={name} type={type} placeholder={placeholder} className="field mt-2"/></label>}
function Select({name,value,onChange,children}:{name:string;value:string;onChange:(e:React.ChangeEvent<HTMLSelectElement>)=>void;children:React.ReactNode}){return <select name={name} value={value} onChange={onChange} className="field">{children}</select>}
function TextArea({name,label}:{name:string;label:string}){return <label className="mt-3 block text-sm font-bold"><span>{label}</span><textarea name={name} rows={3} className="field mt-2 resize-y"/></label>}
function PhotoPreview({file,onRemove}:{file:File;onRemove:()=>void}){const url=URL.createObjectURL(file);return <div className="relative overflow-hidden rounded-xl border border-black/8 bg-black/[.03]"><img src={url} alt={file.name} className="aspect-video w-full object-cover"/><button type="button" onClick={onRemove} className="absolute right-2 top-2 rounded-lg bg-black/70 p-2 text-white"><Trash2 className="size-4"/></button><p className="truncate px-2 py-2 text-[10px] font-bold">{file.name}</p></div>}
