import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, FileText, Loader2, MessageCircle, Plus, ReceiptText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { ManualItemsEditor } from "@/components/admin/ManualItemsEditor";
import { createQuote, convertQuoteToWorkOrder, openQuoteWhatsApp, updateQuoteStatus, useQuotes } from "@/lib/quote-operations";
import { money, useCustomers } from "@/lib/porfirid-queries";
import type { ManualLineItem } from "@/lib/work-order-intake-v2";

const db=supabase as any;
const blankLine=():ManualLineItem=>({description:"",quantity:1,unit_price:0});
const statusLabel:Record<string,string>={rascunho:"Rascunho",enviado:"Enviado",aprovado:"Aprovado",recusado:"Recusado",convertido:"Convertido em OS",cancelado:"Cancelado"};

export function QuotesManager({onOpenOrder}:{onOpenOrder:(id:string)=>void}){
 const qc=useQueryClient();const {data:quotes=[],isLoading}=useQuotes();const {data:customers=[]}=useCustomers();
 const {data:vehicles=[]}=useQuery({queryKey:["quote_vehicle_options"],queryFn:async()=>{const {data,error}=await db.from("vehicles").select("id,customer_id,plate,brand,model").order("created_at",{ascending:false});if(error)throw error;return data??[];}});
 const [show,setShow]=useState(false),[customerMode,setCustomerMode]=useState<"existing"|"new">(customers.length?"existing":"new"),[customerId,setCustomerId]=useState(""),[vehicleMode,setVehicleMode]=useState<"existing"|"new">("new"),[vehicleId,setVehicleId]=useState("");
 const [parts,setParts]=useState<ManualLineItem[]>([blankLine()]),[labor,setLabor]=useState<ManualLineItem[]>([blankLine()]),[discount,setDiscount]=useState(0),[working,setWorking]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const customerVehicles=useMemo(()=>vehicles.filter((v:any)=>v.customer_id===customerId),[vehicles,customerId]);const total=Math.max([...parts,...labor].reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unit_price||0),0)-discount,0);
 async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:["quotes"]}),qc.invalidateQueries({queryKey:["customers"]}),qc.invalidateQueries({queryKey:["vehicles"]}),qc.invalidateQueries({queryKey:["quote_vehicle_options"]}),qc.invalidateQueries({queryKey:["work_orders"]}),qc.invalidateQueries({queryKey:["dashboard"]})])}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setError(null);setMessage(null);const cleanParts=parts.filter(i=>i.description.trim()),cleanLabor=labor.filter(i=>i.description.trim());if(!cleanParts.length&&!cleanLabor.length)return setError("Informe pelo menos uma peça ou mão de obra.");if(customerMode==="existing"&&!customerId)return setError("Selecione o cliente.");if(customerMode==="new"&&(!String(form.get("customer_name")||"").trim()||!String(form.get("customer_phone")||"").trim()))return setError("Informe nome e WhatsApp do cliente.");if(vehicleMode==="existing"&&!vehicleId)return setError("Selecione o veículo.");if(vehicleMode==="new"&&["plate","brand","model"].some(n=>!String(form.get(n)||"").trim()))return setError("Informe placa, marca e modelo.");setWorking("create");try{const result=await createQuote({customer:customerMode==="existing"?{id:customerId}:{name:String(form.get("customer_name")||"").trim(),phone:String(form.get("customer_phone")||"").trim(),cpf_cnpj:String(form.get("cpf_cnpj")||"").trim(),email:String(form.get("customer_email")||"").trim(),city:String(form.get("city")||"").trim(),state:String(form.get("state")||"").trim().toUpperCase()},vehicle:vehicleMode==="existing"?{id:vehicleId}:{plate:String(form.get("plate")||"").trim().toUpperCase(),brand:String(form.get("brand")||"").trim(),model:String(form.get("model")||"").trim(),version:String(form.get("version")||"").trim(),year:String(form.get("year")||"").trim(),model_year:String(form.get("model_year")||"").trim(),color:String(form.get("color")||"").trim(),fuel:String(form.get("fuel")||"").trim()},quote:{valid_until:String(form.get("valid_until")||"").trim(),notes:String(form.get("notes")||"").trim(),discount},parts:cleanParts,labor:cleanLabor});await refresh();setMessage(`Orçamento #${result.quoteNumber} criado em ${money(result.total)}.`);setShow(false);setParts([blankLine()]);setLabor([blankLine()]);setDiscount(0);setCustomerId("");setVehicleId("");e.currentTarget.reset();}catch(err){setError(err instanceof Error?err.message:"Erro ao criar orçamento.");}finally{setWorking(null)}}
 async function convert(q:any){if(!confirm(`Transformar o orçamento #${q.quote_number} em Ordem de Serviço?`))return;setWorking(`convert-${q.id}`);setError(null);try{const r=await convertQuoteToWorkOrder(q.id);await refresh();setMessage(`Convertido em OS #${r.orderNumber}.`);onOpenOrder(r.id)}catch(err){setError(err instanceof Error?err.message:"Erro na conversão.")}finally{setWorking(null)}}
 function printQuote(q:any){const items=q.quote_items??[];const win=window.open("","_blank","width=900,height=800");if(!win)return;win.document.write(`<html><head><title>Orçamento #${q.quote_number}</title><style>body{font-family:Arial;padding:32px;color:#111}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:24px}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:24px;font-weight:800;margin-top:24px}</style></head><body><h1>COMPACT Centro Automotivo</h1><p>Orçamento #${q.quote_number}</p><p><strong>${q.customers?.name??"Cliente"}</strong><br>${q.vehicles?.brand??""} ${q.vehicles?.model??""} • ${q.vehicles?.plate??""}</p><table><thead><tr><th>Item</th><th>Qtd.</th><th>Unit.</th><th>Total</th></tr></thead><tbody>${items.map((i:any)=>`<tr><td>${i.description}</td><td>${i.quantity}</td><td>${money(i.unit_price)}</td><td>${money(Number(i.quantity)*Number(i.unit_price))}</td></tr>`).join("")}</tbody></table><p class="total">Total: ${money(q.total)}</p><script>window.onload=()=>window.print()</script></body></html>`);win.document.close()}
 return <div className="space-y-5"><div className="flex flex-col gap-4 rounded-2xl border border-black/6 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Orçamentos</h2><p className="mt-1 text-sm text-black/45">Peças, mão de obra, PDF, WhatsApp e conversão direta em OS.</p></div><button onClick={()=>setShow(!show)} className="goldButton"><Plus className="size-4"/>{show?"Fechar":"Novo orçamento"}</button></div>{(message||error)&&<div className={`rounded-xl px-4 py-3 text-sm font-bold ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error??message}</div>}
 {show&&<form onSubmit={submit} className="overflow-hidden rounded-3xl border border-[#F0B323]/30 bg-white shadow-sm"><div className="bg-[#111214] p-5 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Novo orçamento</p><h3 className="mt-1 text-xl font-black">Cliente, veículo, peças e serviços</h3></div><div className="space-y-6 p-5 sm:p-6"><Section title="1. Cliente"><ModeSwitch value={customerMode} onChange={v=>{setCustomerMode(v);setCustomerId("");setVehicleId("");setVehicleMode("new")}} existingLabel={`Existente (${customers.length})`} newLabel="Novo" disableExisting={!customers.length}/>{customerMode==="existing"?<label className="mt-3 block text-sm font-bold">Cliente *<select className="field mt-2" value={customerId} onChange={e=>{setCustomerId(e.target.value);setVehicleId("");setVehicleMode(vehicles.some((v:any)=>v.customer_id===e.target.value)?"existing":"new")}}><option value="">Selecione...</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</select></label>:<div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field name="customer_name" label="Nome *"/><Field name="customer_phone" label="WhatsApp *"/><Field name="cpf_cnpj" label="CPF / CNPJ"/><Field name="customer_email" label="E-mail" type="email"/><Field name="city" label="Cidade"/><Field name="state" label="UF" maxLength={2}/></div>}</Section>
 <Section title="2. Veículo">{customerMode==="existing"&&customerId&&<ModeSwitch value={vehicleMode} onChange={v=>{setVehicleMode(v);setVehicleId("")}} existingLabel={`Existente (${customerVehicles.length})`} newLabel="Novo" disableExisting={!customerVehicles.length}/>} {vehicleMode==="existing"&&customerMode==="existing"?<label className="mt-3 block text-sm font-bold">Veículo *<select className="field mt-2" value={vehicleId} onChange={e=>setVehicleId(e.target.value)}><option value="">Selecione...</option>{customerVehicles.map((v:any)=><option key={v.id} value={v.id}>{v.brand} {v.model} • {v.plate}</option>)}</select></label>:<div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field name="plate" label="Placa *"/><Field name="brand" label="Marca *"/><Field name="model" label="Modelo *"/><Field name="version" label="Versão"/><Field name="year" label="Ano" type="number"/><Field name="model_year" label="Ano modelo" type="number"/><Field name="color" label="Cor"/><Field name="fuel" label="Combustível"/></div>}</Section>
 <Section title="3. Peças"><ManualItemsEditor title="Peças do orçamento" subtitle="Selecione do estoque ou inclua itens manuais." singular="peça" items={parts} onChange={setParts}/></Section><Section title="4. Mão de obra"><ManualItemsEditor title="Mão de obra" subtitle="Inclua todos os serviços previstos." singular="mão de obra" items={labor} onChange={setLabor}/></Section><Section title="5. Condições"><div className="grid gap-3 md:grid-cols-3"><Field name="valid_until" label="Validade" type="date"/><label className="text-sm font-bold">Desconto<input type="number" min="0" step="0.01" className="field mt-2" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><div className="rounded-2xl bg-[#111214] p-4 text-white"><p className="text-xs text-white/45">Total do orçamento</p><p className="mt-1 text-2xl font-black text-[#FFC43D]">{money(total)}</p></div></div><label className="mt-3 block text-sm font-bold">Observações<textarea name="notes" rows={3} className="field mt-2"/></label></Section><button disabled={working==="create"} className="goldButton w-full justify-center py-4">{working==="create"&&<Loader2 className="size-4 animate-spin"/>}Finalizar orçamento</button></div></form>}
 {isLoading?<div className="rounded-2xl bg-white p-8 text-center text-sm text-black/40">Carregando...</div>:quotes.length===0?<div className="rounded-2xl border border-dashed border-black/12 bg-white p-10 text-center"><ReceiptText className="mx-auto size-8 text-[#B97900]"/><p className="mt-3 font-black">Nenhum orçamento ainda.</p></div>:<div className="space-y-3">{quotes.map((q:any)=><article key={q.id} className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 xl:flex-row xl:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-lg font-black text-[#9B6600]">Orçamento #{q.quote_number}</span><span className="rounded-full bg-black/5 px-2.5 py-1 text-[10px] font-black uppercase">{statusLabel[q.status]??q.status}</span></div><p className="mt-2 font-bold">{q.customers?.name??"Cliente"}</p><p className="mt-1 text-xs text-black/45">{q.vehicles?.brand} {q.vehicles?.model} • {q.vehicles?.plate}</p></div><p className="text-xl font-black">{money(q.total)}</p><div className="flex flex-wrap gap-2"><button onClick={()=>printQuote(q)} className="secondaryButton"><FileText className="size-4"/>Imprimir</button><button onClick={()=>{try{openQuoteWhatsApp(q);void updateQuoteStatus(q.id,"enviado").then(refresh)}catch(e){setError(e instanceof Error?e.message:"Erro")}}} className="secondaryButton"><MessageCircle className="size-4"/>WhatsApp</button>{q.status!=="convertido"&&<button disabled={working===`convert-${q.id}`} onClick={()=>void convert(q)} className="goldButton"><CheckCircle2 className="size-4"/>Converter em OS</button>}</div></div></article>)}</div>}</div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><p className="mb-3 text-xs font-black uppercase tracking-[.15em] text-black/42">{title}</p>{children}</section>}
function ModeSwitch({value,onChange,existingLabel,newLabel,disableExisting=false}:{value:"existing"|"new";onChange:(v:"existing"|"new")=>void;existingLabel:string;newLabel:string;disableExisting?:boolean}){return <div className="inline-flex rounded-xl bg-black/5 p-1"><button type="button" disabled={disableExisting} onClick={()=>onChange("existing")} className={`rounded-lg px-3 py-2 text-xs font-black ${value==="existing"?"bg-[#F0B323] text-black":"text-black/45"} disabled:opacity-35`}>{existingLabel}</button><button type="button" onClick={()=>onChange("new")} className={`rounded-lg px-3 py-2 text-xs font-black ${value==="new"?"bg-[#F0B323] text-black":"text-black/45"}`}>{newLabel}</button></div>}
function Field({name,label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{name:string;label:string}){return <label className="text-sm font-bold">{label}<input name={name} {...props} className="field mt-2"/></label>}
