import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Building2, CheckCircle2, FileText, MessageCircle, Save, Settings2, ShieldCheck, WalletCards } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const empty:any={trade_name:"",company_name:"",cnpj:"",phone:"",whatsapp:"",email:"",website:"",slogan:"",street:"",address_number:"",neighborhood:"",city:"",state:"",zip_code:"",complement:"",business_hours:"",document_header_note:"",document_footer_note:"",quote_terms:"",work_order_terms:"",receipt_note:"",whatsapp_greeting:"",whatsapp_quote_message:"",whatsapp_tracking_message:"",whatsapp_ready_message:"",quote_validity_days:7,default_warranty_days:90,require_payment_before_delivery:true,allow_partial_approval:true,tracking_enabled:true,payment_methods:["PIX","Dinheiro","Débito","Crédito","Transferência","Outro"]};
const sections=[{id:"company",label:"Dados da empresa",icon:Building2},{id:"documents",label:"Documentos",icon:FileText},{id:"whatsapp",label:"WhatsApp",icon:MessageCircle},{id:"rules",label:"Regras",icon:ShieldCheck},{id:"payments",label:"Pagamentos",icon:WalletCards}] as const;
type SectionId=(typeof sections)[number]["id"];
const paymentOptions=["PIX","Dinheiro","Débito","Crédito","Transferência","Boleto","Outro"];

export function SettingsManager(){
 const queryClient=useQueryClient();
 const [form,setForm]=useState<any>(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[active,setActive]=useState<SectionId>("company");
 useEffect(()=>{void supabase.from("app_settings").select("*").eq("id",1).maybeSingle().then(({data})=>{if(data)setForm({...empty,...data});setLoading(false)})},[]);
 const address=useMemo(()=>[form.street,form.address_number&&`nº ${form.address_number}`,form.complement,form.neighborhood,[form.city,form.state].filter(Boolean).join(" - ")].filter(Boolean).join(", "),[form]);
 function set(k:string,v:any){setForm((f:any)=>({...f,[k]:v}));setMessage("")}
 async function save(){setSaving(true);setMessage("");const {data:auth}=await supabase.auth.getUser();const payload={...form,id:1,updated_at:new Date().toISOString(),updated_by:auth.user?.id??null};const {error}=await supabase.from("app_settings").upsert(payload);if(!error){queryClient.setQueryData(["app_settings"],payload);await queryClient.invalidateQueries({queryKey:["app_settings"]});}setSaving(false);setMessage(error?error.message:"Configurações salvas com sucesso e aplicadas imediatamente.")}
 if(loading)return <div className="rounded-2xl bg-white p-10 text-center">Carregando...</div>;
 return <div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#9B6600]">Administração</p><h2 className="mt-1 text-2xl font-black">Configurações</h2><p className="mt-1 text-sm text-black/50">Dados da empresa, documentos, mensagens, regras operacionais e formas de pagamento.</p></div>
 <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{sections.map(s=>{const I=s.icon,on=active===s.id;return <button key={s.id} onClick={()=>setActive(s.id)} className={`rounded-2xl border p-4 text-left ${on?"border-[#F0B323] bg-[#F0B323]/5":"border-black/7 bg-white"}`}><div className={`flex size-10 items-center justify-center rounded-xl ${on?"bg-[#F0B323] text-black":"bg-[#F0B323]/15 text-[#8A5F00]"}`}><I className="size-5"/></div><p className="mt-3 text-sm font-black">{s.label}</p></button>})}</div>
 {message&&<p className="rounded-xl bg-[#F0B323]/12 px-4 py-3 text-sm font-bold text-[#6F4B00]">{message}</p>}
 <section className="rounded-3xl border border-black/6 bg-white p-5 shadow-sm sm:p-6">
 {active==="company"&&<><Title title="Dados da empresa" subtitle="Informações cadastrais e endereço da oficina."/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Nome da empresa" value={form.company_name} onChange={v=>set("company_name",v)}/><Field label="Nome fantasia" value={form.trade_name} onChange={v=>set("trade_name",v)}/><Field label="CNPJ" value={form.cnpj} onChange={v=>set("cnpj",v)}/><Field label="Telefone" value={form.phone} onChange={v=>set("phone",v)}/><Field label="WhatsApp" value={form.whatsapp} onChange={v=>set("whatsapp",v)}/><Field label="E-mail" value={form.email} onChange={v=>set("email",v)}/><Field label="Website" value={form.website} onChange={v=>set("website",v)}/><Field label="Slogan" value={form.slogan} onChange={v=>set("slogan",v)}/><Field label="Horário de atendimento" value={form.business_hours} onChange={v=>set("business_hours",v)}/></div><h4 className="mt-6 font-black">Endereço</h4><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field label="CEP" value={form.zip_code} onChange={v=>set("zip_code",v)}/><Field label="Logradouro" value={form.street} onChange={v=>set("street",v)}/><Field label="Número" value={form.address_number} onChange={v=>set("address_number",v)}/><Field label="Complemento" value={form.complement} onChange={v=>set("complement",v)}/><Field label="Bairro" value={form.neighborhood} onChange={v=>set("neighborhood",v)}/><Field label="Cidade" value={form.city} onChange={v=>set("city",v)}/><Field label="UF" value={form.state} onChange={v=>set("state",v.toUpperCase().slice(0,2))}/></div><div className="mt-4 rounded-xl bg-black/[.025] p-4 text-sm"><b>Prévia:</b> {address||"Endereço não informado"}</div></>}
 {active==="documents"&&<><Title title="Modelos de documentos" subtitle="Textos usados em orçamento, Ordem de Serviço e recibo."/><div className="space-y-4"><TextArea label="Observação do cabeçalho" value={form.document_header_note} onChange={v=>set("document_header_note",v)}/><TextArea label="Termos do orçamento" value={form.quote_terms} onChange={v=>set("quote_terms",v)} rows={4}/><TextArea label="Termos da Ordem de Serviço" value={form.work_order_terms} onChange={v=>set("work_order_terms",v)} rows={4}/><TextArea label="Mensagem do recibo" value={form.receipt_note} onChange={v=>set("receipt_note",v)}/><TextArea label="Rodapé dos documentos" value={form.document_footer_note} onChange={v=>set("document_footer_note",v)}/></div></>}
 {active==="whatsapp"&&<><Title title="Mensagens e WhatsApp" subtitle="Textos padrão para o atendimento ao cliente."/><div className="space-y-4"><TextArea label="Saudação padrão" value={form.whatsapp_greeting} onChange={v=>set("whatsapp_greeting",v)}/><TextArea label="Mensagem de orçamento" value={form.whatsapp_quote_message} onChange={v=>set("whatsapp_quote_message",v)} rows={3}/><TextArea label="Mensagem de acompanhamento" value={form.whatsapp_tracking_message} onChange={v=>set("whatsapp_tracking_message",v)} rows={3}/><TextArea label="Mensagem de veículo pronto" value={form.whatsapp_ready_message} onChange={v=>set("whatsapp_ready_message",v)} rows={3}/></div></>}
 {active==="rules"&&<><Title title="Regras da oficina" subtitle="Parâmetros operacionais padrão."/><div className="grid gap-3 md:grid-cols-2"><NumberField label="Validade padrão do orçamento (dias)" value={form.quote_validity_days} onChange={v=>set("quote_validity_days",v)}/><NumberField label="Garantia padrão informativa (dias)" value={form.default_warranty_days} onChange={v=>set("default_warranty_days",v)}/></div><div className="mt-5 space-y-3"><Toggle label="Exigir pagamento antes de marcar veículo como entregue" checked={!!form.require_payment_before_delivery} onChange={v=>set("require_payment_before_delivery",v)}/><Toggle label="Permitir aprovação parcial de orçamento" checked={!!form.allow_partial_approval} onChange={v=>set("allow_partial_approval",v)}/><Toggle label="Habilitar acompanhamento do veículo por link" checked={!!form.tracking_enabled} onChange={v=>set("tracking_enabled",v)}/></div></>}
 {active==="payments"&&<><Title title="Formas de pagamento" subtitle="Métodos aceitos pela oficina."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{paymentOptions.map(m=>{const checked=(form.payment_methods??[]).includes(m);return <label key={m} className={`flex items-center gap-3 rounded-2xl border p-4 ${checked?"border-emerald-200 bg-emerald-50":"border-black/8 bg-[#fafafa]"}`}><input type="checkbox" checked={checked} onChange={e=>set("payment_methods",e.target.checked?[...(form.payment_methods??[]),m]:(form.payment_methods??[]).filter((x:string)=>x!==m))} className="size-4 accent-[#F0B323]"/><span className="font-black">{m}</span>{checked&&<CheckCircle2 className="ml-auto size-4 text-emerald-600"/>}</label>})}</div></>}
 <div className="mt-6 flex justify-end border-t border-black/6 pt-5"><button onClick={()=>void save()} disabled={saving} className="goldButton"><Save className="size-4"/>{saving?"Salvando...":"Salvar alterações"}</button></div></section>
 <div className="rounded-3xl bg-[#111214] p-5 text-white"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#F0B323]/15 p-2 text-[#FFC43D]"><Settings2 className="size-5"/></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#FFC43D]">Configuração centralizada</p><p className="mt-1 text-sm text-white/55">As regras e textos ficam salvos no banco para uso em toda a oficina.</p></div></div></div></div>;
}
function Title({title,subtitle}:{title:string;subtitle:string}){return <div className="mb-5"><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-sm text-black/45">{subtitle}</p></div>}
function Field({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label className="text-sm font-bold">{label}<input className="field mt-2" value={value??""} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange,rows=3}:{label:string;value:any;onChange:(v:string)=>void;rows?:number}){return <label className="block text-sm font-bold">{label}<textarea className="field mt-2 resize-y" rows={rows} value={value??""} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,onChange}:{label:string;value:any;onChange:(v:number)=>void}){return <label className="text-sm font-bold">{label}<input type="number" min="0" className="field mt-2" value={value??0} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl border border-black/8 p-4 text-sm font-bold"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-4 accent-[#F0B323]"/>{label}</label>}
