import { useEffect, useMemo, useState } from "react";
import { Loader2, PackagePlus, Save, Trash2, UserRoundCog } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
const db=supabase as any;
const statuses=[["pendente","Pendente"],["em_execucao","Em execução"],["concluido","Concluído"]] as const;
export function TechnicianExecutionPanel({workOrderId,locked=false}:{workOrderId:string;locked?:boolean}){
 const [parts,setParts]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[inventory,setInventory]=useState<any[]>([]),[collaborators,setCollaborators]=useState<any[]>([]),[selected,setSelected]=useState(""),[qty,setQty]=useState(1),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 async function load(){const {data,error}=await db.rpc("get_technician_work_order_execution",{p_work_order_id:workOrderId});if(error){setError(error.message);return}setParts(data?.parts??[]);setServices(data?.services??[]);setInventory(data?.inventory??[]);setCollaborators(data?.collaborators??[])}
 useEffect(()=>{void load()},[workOrderId]);
 const selectedItem=useMemo(()=>inventory.find((x:any)=>x.id===selected),[inventory,selected]);
 async function addPart(){if(!selected||qty<=0)return;setBusy(true);setError(null);setMessage(null);const {error}=await db.rpc("technician_add_inventory_part",{p_work_order_id:workOrderId,p_inventory_item_id:selected,p_quantity:qty});setBusy(false);if(error)return setError(error.message);setSelected("");setQty(1);setMessage("Peça lançada e baixada do estoque.");await load()}
 async function removePart(id:string){setBusy(true);setError(null);const {error}=await db.rpc("technician_remove_inventory_part",{p_part_id:id});setBusy(false);if(error)return setError(error.message);setMessage("Peça removida e devolvida ao estoque.");await load()}
 return <div className="space-y-4">{(error||message)&&<p className={`rounded-xl p-3 text-sm font-bold ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error??message}</p>}
 <section className="rounded-2xl border border-black/6 bg-white p-5"><div className="flex items-center gap-2"><PackagePlus className="size-4 text-[#B97900]"/><h3 className="font-black">Peças utilizadas</h3></div>{!locked&&<div className="mt-4 grid gap-3 md:grid-cols-[1.7fr_.45fr_auto]"><select className="field" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecionar peça do estoque...</option>{inventory.map((i:any)=><option key={i.id} value={i.id}>{i.name} • saldo {Number(i.quantity)} {i.unit??"un"}</option>)}</select><input className="field" type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(Number(e.target.value))}/><button disabled={busy||!selected} onClick={()=>void addPart()} className="goldButton">{busy?<Loader2 className="size-4 animate-spin"/>:<PackagePlus className="size-4"/>}Lançar</button></div>}{selectedItem&&<p className="mt-2 text-xs text-black/45">Localização: {selectedItem.location||"—"} • mínimo: {Number(selectedItem.min_quantity||0)} {selectedItem.unit||"un"}</p>}<div className="mt-4 space-y-2">{parts.map((p:any)=><div key={p.id} className="flex items-center gap-3 rounded-xl bg-black/[.025] p-3"><div className="flex-1"><p className="font-bold">{p.description}</p><p className="text-xs text-black/45">Quantidade: {Number(p.quantity)} • {p.origin==="estoque"?"Estoque":"Manual"}</p></div>{!locked&&p.origin==="estoque"&&<button disabled={busy} onClick={()=>void removePart(p.id)} className="rounded-lg border border-red-200 p-2 text-red-700"><Trash2 className="size-4"/></button>}{p.origin==="manual"&&<span className="text-xs text-black/35">Alteração pelo atendimento</span>}</div>)}{parts.length===0&&<p className="text-sm text-black/40">Nenhuma peça lançada.</p>}</div></section>
 <section className="rounded-2xl border border-black/6 bg-white p-5"><div className="flex items-center gap-2"><UserRoundCog className="size-4 text-[#B97900]"/><h3 className="font-black">Execução dos serviços</h3></div><div className="mt-4 space-y-3">{services.map((s:any)=><TechnicianServiceRow key={s.id} service={s} collaborators={collaborators} locked={locked} onSaved={load}/>) }{services.length===0&&<p className="text-sm text-black/40">Nenhum serviço lançado.</p>}</div></section>
 </div>}
function TechnicianServiceRow({service,collaborators,locked,onSaved}:{service:any;collaborators:any[];locked:boolean;onSaved:()=>Promise<void>}){const [collaboratorId,setCollaboratorId]=useState(service.collaborator_id??""),[status,setStatus]=useState(service.status??"pendente"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);useEffect(()=>{setCollaboratorId(service.collaborator_id??"");setStatus(["pendente","em_execucao","concluido"].includes(service.status)?service.status:"pendente")},[service.collaborator_id,service.status]);const dirty=collaboratorId!==(service.collaborator_id??"")||status!==service.status;async function save(){setBusy(true);setError(null);const {error}=await db.rpc("technician_update_service_execution",{p_service_id:service.id,p_collaborator_id:collaboratorId||null,p_status:status});setBusy(false);if(error)return setError(error.message);await onSaved()}return <div className="rounded-xl bg-black/[.025] p-4"><p className="font-black">{service.description}</p><p className="mt-1 text-xs text-black/45">Quantidade: {Number(service.quantity||1)}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><select disabled={locked||busy} className="field" value={collaboratorId} onChange={e=>setCollaboratorId(e.target.value)}><option value="">Responsável...</option>{collaborators.map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.job_title?` • ${c.job_title}`:""}</option>)}</select><select disabled={locked||busy} className="field" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{!locked&&<button disabled={busy||!dirty} onClick={()=>void save()} className="goldButton">{busy?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Salvar</button>}</div>{error&&<p className="mt-2 text-xs font-bold text-red-700">{error}</p>}</div>}
