import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, History, PackagePlus, Search, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
const db=supabase as any;
export function TechnicianStockManager(){
 const [rows,setRows]=useState<any[]>([]),[moves,setMoves]=useState<any[]>([]),[search,setSearch]=useState(""),[historyId,setHistoryId]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);const {data,error}=await db.rpc("get_technician_stock_snapshot");if(error)setError(error.message);else{setRows(data?.items??[]);setMoves(data?.movements??[])}setLoading(false)}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>!search||[r.name,r.sku,r.barcode,r.category,r.ncm,r.location].some((v:any)=>String(v??"").toLowerCase().includes(search.toLowerCase()))),[rows,search]);
 const low=rows.filter(r=>r.active!==false&&Number(r.quantity)<=Number(r.min_quantity)).length;
 return <div className="space-y-5"><div className="rounded-3xl bg-[#111214] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-[#F0B323]">Estoque • modo técnico</p><h2 className="mt-1 text-2xl font-black">Peças e materiais</h2><p className="mt-2 text-sm text-white/45">Saldo, localização, estoque mínimo e movimentações operacionais. Custos, preços e fornecedores ficam restritos aos perfis administrativos.</p></div><div className="grid gap-3 sm:grid-cols-2"><Stat label="Itens cadastrados" value={rows.length}/><Stat label="Estoque baixo" value={low}/></div>{(error||message)&&<div className={`rounded-xl p-3 text-sm font-bold ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error??message}</div>}<div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-black/30"/><input value={search} onChange={e=>setSearch(e.target.value)} className="field pl-10" placeholder="Buscar peça, SKU, código, categoria ou localização..."/></div>{loading?<div className="rounded-2xl bg-white p-8">Carregando...</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(row=>{const isLow=Number(row.quantity)<=Number(row.min_quantity);return <article key={row.id} className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className={`flex size-11 items-center justify-center rounded-xl ${isLow?"bg-amber-100 text-amber-700":"bg-[#F0B323]/15 text-[#8A5F00]"}`}>{isLow?<AlertTriangle className="size-5"/>:<PackagePlus className="size-5"/>}</div><div className="min-w-0 flex-1"><h3 className="truncate font-black">{row.name}</h3><p className="mt-1 text-xs text-black/40">{row.sku||"Sem SKU"} • {row.category||"Sem categoria"}</p><p className="mt-1 text-[11px] text-black/35">{row.barcode?`EAN: ${row.barcode} • `:""}{row.ncm?`NCM: ${row.ncm} • `:""}{row.location||"Sem localização"}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Mini label="Saldo" value={`${Number(row.quantity||0)} ${row.unit||"un"}`}/><Mini label="Mínimo" value={`${Number(row.min_quantity||0)} ${row.unit||"un"}`}/></div>{isLow&&<p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Estoque abaixo ou no mínimo.</p>}<button onClick={()=>setHistoryId(row.id)} className="secondaryButton mt-4"><History className="size-4"/>Histórico / movimentar</button></article>})}</div>}{historyId&&<MovementModal item={rows.find(r=>r.id===historyId)} rows={moves.filter(m=>m.inventory_item_id===historyId)} onClose={()=>setHistoryId(null)} onSaved={async()=>{setHistoryId(null);setMessage("Movimentação registrada.");await load()}}/>}</div>;
}
function MovementModal({item,rows,onClose,onSaved}:{item:any;rows:any[];onClose:()=>void;onSaved:()=>Promise<void>}){const [type,setType]=useState("entrada"),[qty,setQty]=useState("1"),[reason,setReason]=useState("Ajuste operacional"),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);async function move(){const q=Number(qty);if(!Number.isFinite(q)||q<0)return setError("Informe uma quantidade válida.");if((type==="entrada"||type==="saida")&&q<=0)return setError("Informe uma quantidade maior que zero.");setSaving(true);const {error}=await db.rpc("adjust_inventory_stock",{p_inventory_item_id:item.id,p_quantity:q,p_type:type,p_reason:reason.trim()||"Ajuste operacional",p_unit_cost:null});setSaving(false);if(error)return setError(error.message);await onSaved()}return <div className="fixed inset-0 z-[90] overflow-y-auto bg-black/60 p-4"><div className="mx-auto my-8 max-w-2xl rounded-3xl bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#B97900]">Movimentações</p><h3 className="text-xl font-black">{item?.name??"Item"}</h3></div><button onClick={onClose}><X/></button></div><div className="mt-4 rounded-xl bg-black/[.03] p-3 text-sm"><strong>Saldo atual:</strong> {Number(item?.quantity||0)} {item?.unit||"un"}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="entrada">Entrada</option><option value="saida">Saída</option><option value="ajuste">Definir saldo</option></select><input className="field" type="number" min="0" step="0.01" value={qty} onChange={e=>setQty(e.target.value)}/><button className="goldButton" disabled={saving} onClick={()=>void move()}>{saving?"Registrando...":"Registrar"}</button></div><input className="field mt-3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo da movimentação"/>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-5"><p className="text-xs font-black uppercase tracking-wider text-black/35">Histórico recente</p><div className="mt-2 max-h-72 space-y-2 overflow-y-auto">{rows.map(r=><div key={r.id} className="rounded-xl bg-black/[.025] p-3 text-xs"><div className="flex justify-between gap-3"><b>{String(r.movement_type).toUpperCase()} • {Number(r.quantity)} {item?.unit||"un"}</b><span className="text-black/35">{new Date(r.created_at).toLocaleString("pt-BR")}</span></div><p className="mt-1 text-black/55">{r.reason||"Sem motivo informado"}</p></div>)}{rows.length===0&&<p className="text-sm text-black/40">Sem movimentações recentes.</p>}</div></div></div></div>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-black/6 bg-white p-4"><p className="text-[10px] font-black uppercase tracking-wider text-black/35">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/[.03] p-3"><p className="text-[10px] font-black uppercase text-black/35">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
