import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Car, ClipboardList, PackageSearch, ReceiptText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { STATUS_LABEL, type OrderStatus } from "@/lib/porfirid-queries";

const db=supabase as any;

export function TechnicianDashboard({onOpenOrder}:{onOpenOrder:(id:string)=>void}){
 const [orders,setOrders]=useState<any[]>([]),[vehicles,setVehicles]=useState<any[]>([]),[lowStock,setLowStock]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 useEffect(()=>{void(async()=>{setLoading(true);setError(null);const[o,v,i]=await Promise.all([db.rpc("get_technician_work_orders"),db.rpc("get_technician_vehicle_directory"),db.from("inventory_items").select("id,quantity,min_quantity,active")]);const e=o.error||v.error||i.error;if(e)setError(e.message);setOrders(o.data??[]);setVehicles(v.data??[]);setLowStock((i.data??[]).filter((x:any)=>x.active!==false&&Number(x.quantity)<=Number(x.min_quantity)).length);setLoading(false)})()},[]);
 const metrics=useMemo(()=>({open:orders.filter(o=>!["entregue","cancelada"].includes(o.status)).length,approval:orders.filter(o=>o.status==="aguardando_aprovacao").length,ready:orders.filter(o=>o.status==="pronto_entrega").length}),[orders]);
 if(error)return <div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>;
 return <div className="space-y-6"><div className="rounded-[2rem] bg-[#111214] p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[#F0B323]">Central técnica</p><h2 className="mt-2 text-3xl font-black">Visão operacional da oficina</h2><p className="mt-2 text-sm text-white/45">Somente dados necessários para execução, diagnóstico e andamento das OS.</p></div>{loading?<div className="h-32 animate-pulse rounded-3xl bg-black/5"/>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="OS abertas" value={metrics.open} icon={ClipboardList}/><Metric label="Aguardando aprovação" value={metrics.approval} icon={ReceiptText}/><Metric label="Prontas para entrega" value={metrics.ready} icon={Car}/><Metric label="Veículos" value={vehicles.length} icon={Car}/><Metric label="Estoque baixo" value={lowStock} icon={PackageSearch}/></div><Attention label="Itens com estoque baixo" value={String(lowStock)} danger={lowStock>0}/></>}<section className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div><h3 className="font-black">Últimas ordens de serviço</h3><p className="mt-1 text-xs text-black/40">Acesso rápido aos atendimentos operacionais mais recentes.</p></div><div className="mt-4 space-y-2">{orders.slice(0,8).map((r:any)=><button key={r.id} onClick={()=>onOpenOrder(r.id)} className="flex w-full flex-col gap-2 rounded-xl border border-black/7 p-3 text-left hover:border-[#F0B323]/50 sm:flex-row sm:items-center"><strong className="text-[#8A5F00]">OS #{r.order_number}</strong><span className="flex-1 text-sm">{r.customer_name||"Cliente"} • {[r.vehicle_brand,r.vehicle_model].filter(Boolean).join(" ")} • {r.vehicle_plate||"—"}</span><span className="rounded-full bg-[#F0B323]/15 px-2.5 py-1 text-[10px] font-black uppercase text-[#7A5400]">{STATUS_LABEL[r.status as OrderStatus]??r.status}</span></button>)}{orders.length===0&&<p className="py-6 text-center text-sm text-black/40">Nenhuma OS registrada.</p>}</div></section></div>
}
function Metric({label,value,icon:I}:{label:string;value:string|number;icon:any}){return <div className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/15 text-[#8A5F00]"><I className="size-5"/></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Attention({label,value,danger}:{label:string;value:string;danger:boolean}){return <div className={`flex items-center gap-3 rounded-2xl border p-4 ${danger?"border-amber-200 bg-amber-50":"border-black/6 bg-white"}`}><div className={`flex size-10 items-center justify-center rounded-xl ${danger?"bg-amber-100 text-amber-700":"bg-black/5 text-black/35"}`}><AlertTriangle className="size-5"/></div><div><p className="text-xs font-bold text-black/45">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div></div>}
