import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, KeyRound, Loader2, Pencil, Plus, ShieldCheck, Trash2, UserCog, UserRoundCheck, UserRoundX, X } from "lucide-react";
import { deleteStaffAccess, manageStaffAccess, STAFF_ROLE_LABEL, useStaffAccess, type StaffAccessRow, type StaffRole } from "@/lib/staff-access";
import { supabase } from "@/integrations/supabase/client";

type FormState={email:string;fullName:string;role:StaffRole;active:boolean};
const emptyForm:FormState={email:"",fullName:"",role:"atendimento",active:true};
const roleOptions:[StaffRole,string][]=[["admin","Administrador"],["atendimento","Atendimento"],["tecnico","Técnico"],["financeiro","Financeiro"]];

export function UserManagement(){
 const queryClient=useQueryClient();const {data=[],isLoading,error}=useStaffAccess(true);
 const [form,setForm]=useState<FormState>(emptyForm),[editingEmail,setEditingEmail]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[working,setWorking]=useState(false),[deletingEmail,setDeletingEmail]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[actionError,setActionError]=useState<string|null>(null),[currentEmail,setCurrentEmail]=useState("");
 useEffect(()=>{void supabase.auth.getUser().then(({data:auth})=>setCurrentEmail(auth.user?.email?.toLowerCase()??""))},[]);
 const counts=useMemo(()=>({total:data.length,active:data.filter(i=>i.active).length,admins:data.filter(i=>i.active&&i.role==="admin").length,pending:data.filter(i=>i.active&&!i.has_account).length}),[data]);
 function startNew(){setEditingEmail(null);setForm(emptyForm);setMessage(null);setActionError(null);setShowForm(true)}
 function startEdit(item:StaffAccessRow){setEditingEmail(item.email);setForm({email:item.email,fullName:item.full_name,role:(roleOptions.some(([v])=>v===item.role)?item.role:"atendimento") as StaffRole,active:item.active});setMessage(null);setActionError(null);setShowForm(true)}
 async function save(e:React.FormEvent){e.preventDefault();setWorking(true);setMessage(null);setActionError(null);try{await manageStaffAccess(form);await queryClient.invalidateQueries({queryKey:["staff_access"]});setMessage(editingEmail?"Acesso atualizado.":"Usuário autorizado. Ele já pode usar Primeiro acesso para criar a senha.");setShowForm(false);setEditingEmail(null);setForm(emptyForm)}catch(err){setActionError(err instanceof Error?err.message:"Não foi possível salvar o usuário.")}finally{setWorking(false)}}
 async function removeUser(item:StaffAccessRow){const isSelf=item.email.toLowerCase()===currentEmail;if(isSelf)return setActionError("Você não pode excluir sua própria conta.");if(item.role==="admin"&&item.active&&counts.admins<=1)return setActionError("Não é possível excluir o último administrador ativo.");if(!window.confirm(`Excluir ${item.full_name} (${item.email})?\n\nO acesso será removido, preservando o histórico operacional.`))return;setDeletingEmail(item.email);setMessage(null);setActionError(null);try{await deleteStaffAccess(item.email);await queryClient.invalidateQueries({queryKey:["staff_access"]});setMessage("Usuário excluído com sucesso.")}catch(err){setActionError(err instanceof Error?err.message:"Não foi possível excluir o usuário.")}finally{setDeletingEmail(null)}}
 return <div className="space-y-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#B97900]">Administração</p><h2 className="mt-1 text-2xl font-black">Usuários e acessos</h2><p className="mt-1 max-w-3xl text-sm leading-relaxed text-black/50">Autorize o e-mail, defina a função e o colaborador cria a própria senha no primeiro acesso.</p></div><button onClick={startNew} className="goldButton"><Plus className="size-4"/>Novo usuário</button></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Usuários" value={counts.total}/><Metric label="Ativos" value={counts.active}/><Metric label="Administradores" value={counts.admins}/><Metric label="Aguardando 1º acesso" value={counts.pending}/></div>
  <div className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex items-start gap-3 rounded-2xl border border-[#F0B323]/20 bg-[#F0B323]/[.05] p-4"><div className="rounded-xl bg-[#F0B323]/15 p-2 text-[#8A5F00]"><KeyRound className="size-4"/></div><div><p className="text-sm font-black">Como funciona o primeiro acesso</p><p className="mt-1 text-xs leading-relaxed text-black/55">Cadastre nome, e-mail e função. Depois o colaborador abre a tela de login, escolhe Primeiro acesso e cria a própria senha usando exatamente o e-mail autorizado.</p></div></div>
   {message&&<p className="mt-4 rounded-xl bg-emerald-50 px-3 py-2.5 text-sm font-semibold text-emerald-700">{message}</p>}{actionError&&<p className="mt-4 rounded-xl bg-red-50 px-3 py-2.5 text-sm font-semibold text-red-700">{actionError}</p>}
   {isLoading?<div className="flex min-h-48 items-center justify-center"><Loader2 className="size-6 animate-spin text-[#B97900]"/></div>:error?<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">Não foi possível carregar os usuários.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-black/7 text-[11px] font-black uppercase tracking-wider text-black/35"><th className="pb-3 pr-4">Usuário</th><th className="pb-3 pr-4">Função</th><th className="pb-3 pr-4">Conta</th><th className="pb-3 pr-4">Status</th><th className="pb-3">Ações</th></tr></thead><tbody>{data.map(item=>{const self=item.email.toLowerCase()===currentEmail,lastAdmin=item.role==="admin"&&item.active&&counts.admins<=1;return <tr key={item.email} className="border-b border-black/5 last:border-0"><td className="py-4 pr-4"><p className="text-sm font-black">{item.full_name}{self?" (você)":""}</p><p className="mt-0.5 text-xs text-black/45">{item.email}</p></td><td className="py-4 pr-4"><span className="rounded-full bg-[#F0B323]/12 px-2.5 py-1 text-[10px] font-black text-[#7A5400]">{STAFF_ROLE_LABEL[item.role]??item.role}</span></td><td className="py-4 pr-4">{item.has_account?<span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-4"/>Acesso criado</span>:<span className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-700"><KeyRound className="size-4"/>Aguardando</span>}</td><td className="py-4 pr-4">{item.active?<span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700"><UserRoundCheck className="size-4"/>Ativo</span>:<span className="inline-flex items-center gap-1.5 text-xs font-bold text-black/40"><UserRoundX className="size-4"/>Bloqueado</span>}</td><td className="py-4"><div className="flex gap-2"><button onClick={()=>startEdit(item)} className="inline-flex items-center gap-2 rounded-lg border border-black/10 px-3 py-2 text-xs font-black"><Pencil className="size-3.5"/>Editar</button><button disabled={self||lastAdmin||deletingEmail===item.email} onClick={()=>void removeUser(item)} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700 disabled:opacity-35">{deletingEmail===item.email?<Loader2 className="size-3.5 animate-spin"/>:<Trash2 className="size-3.5"/>}Excluir</button></div></td></tr>})}</tbody></table></div>}
  </div>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{roleOptions.map(([role,label])=><div key={role} className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><div className="flex size-10 items-center justify-center rounded-xl bg-[#F0B323]/15 text-[#8A5F00]">{role==="admin"?<ShieldCheck className="size-5"/>:<UserCog className="size-5"/>}</div><h3 className="mt-3 font-black">{label}</h3><p className="mt-1 text-xs leading-6 text-black/45">{role==="admin"?"Acesso total.":role==="atendimento"?"Clientes, veículos, orçamentos, OS e agenda.":role==="tecnico"?"OS, veículos, serviços e estoque.":"Financeiro, compras, comissões e relatórios."}</p></div>)}</div>
  {showForm&&<div className="fixed inset-0 z-[100] overflow-y-auto bg-black/65 p-4 backdrop-blur-sm"><button className="fixed inset-0" onClick={()=>!working&&setShowForm(false)} aria-label="Fechar"/><form onSubmit={save} className="relative mx-auto mt-10 w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#B97900]">Acesso ao sistema</p><h3 className="mt-1 text-xl font-black">{editingEmail?"Editar usuário":"Cadastrar usuário"}</h3></div><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl border border-black/10 p-2.5"><X className="size-4"/></button></div><div className="mt-6 space-y-4"><label className="block text-sm font-bold">Nome completo<input required className="field mt-1" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label className="block text-sm font-bold">E-mail de acesso<input required type="email" disabled={Boolean(editingEmail)} className="field mt-1 disabled:bg-black/[.03]" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="block text-sm font-bold">Função<select className="field mt-1" value={form.role} onChange={e=>setForm({...form,role:e.target.value as StaffRole})}>{roleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="flex items-start gap-3 rounded-2xl border border-black/7 p-4"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} className="mt-1 size-4 accent-[#F0B323]"/><span><strong className="block text-sm">Usuário ativo</strong><span className="text-xs text-black/45">Desative para bloquear o acesso sem perder o histórico.</span></span></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setShowForm(false)} className="secondaryButton">Cancelar</button><button disabled={working} className="goldButton">{working?<Loader2 className="size-4 animate-spin"/>:<ShieldCheck className="size-4"/>}Salvar acesso</button></div></form></div>}
 </div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-black/45">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
