import { useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Car, Edit3, History, Loader2, Plus, Search, Trash2, X } from "lucide-react";
import { createVehicle, deleteVehicle, updateVehicle, useVehicleDirectory, useVehicleHistory, type VehicleInput } from "@/lib/customer-vehicle-operations";
import { money, STATUS_LABEL, useCustomers, type OrderStatus } from "@/lib/porfirid-queries";

const blank: VehicleInput = { customer_id:"", plate:"", brand:"", model:"", version:"", year:"", model_year:"", color:"", fuel:"", vin:"", current_mileage:"", notes:"" };

export function VehiclesManager({ userRole, onOpenOrder }: { userRole?: string; onOpenOrder:(id:string)=>void }) {
  const qc=useQueryClient(); const {data=[],isLoading,error}=useVehicleDirectory(); const [search,setSearch]=useState(""); const [editing,setEditing]=useState<any|null>(null); const [history,setHistory]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  const canWrite=["admin","atendimento"].includes(userRole??"");
  const rows=useMemo(()=>{const t=search.trim().toLowerCase();return !t?data:data.filter((v:any)=>[v.plate,v.brand,v.model,v.version,v.color,v.customers?.name].some(x=>String(x??"").toLowerCase().includes(t)))},[data,search]);
  async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:["vehicle_directory"]}),qc.invalidateQueries({queryKey:["vehicles"]}),qc.invalidateQueries({queryKey:["dashboard"]})])}
  async function save(f:VehicleInput){setBusy(true);setMsg("");try{editing?.id?await updateVehicle(editing.id,f):await createVehicle(f);await refresh();setEditing(null);setMsg("Veículo salvo com sucesso.")}catch(e){setMsg(e instanceof Error?e.message:"Erro ao salvar veículo.")}finally{setBusy(false)}}
  async function remove(v:any){if(!confirm(`Excluir o veículo ${v.plate}?`))return;setBusy(true);try{await deleteVehicle(v.id);await refresh()}catch(e){setMsg(e instanceof Error?e.message:"Erro ao excluir.")}finally{setBusy(false)}}
  if(isLoading)return <p className="p-6">Carregando veículos...</p>; if(error)return <p className="p-6 text-red-600">Não foi possível carregar os veículos.</p>;
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-3.5 size-4 text-black/35"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por placa, modelo, proprietário..."/></div>{canWrite&&<button className="goldButton" onClick={()=>setEditing({})}><Plus className="size-4"/> Novo veículo</button>}</div>{msg&&<div className="rounded-xl border border-black/10 bg-white p-3 text-sm">{msg}</div>}<div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{rows.map((v:any)=><article key={v.id} className="rounded-2xl border border-black/8 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/15"><Car className="size-5 text-[#9B6600]"/></div><div className="min-w-0 flex-1"><h3 className="font-black">{v.brand} {v.model}</h3><p className="text-sm font-bold text-[#9B6600]">{v.plate}</p><p className="text-xs text-black/45">{v.customers?.name??"Sem proprietário"}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-black/[.03] p-2"><b>{v.year??"—"}</b><br/>Ano</div><div className="rounded-xl bg-black/[.03] p-2"><b>{Number(v.current_mileage??0).toLocaleString("pt-BR")}</b><br/>Km</div><div className="rounded-xl bg-black/[.03] p-2"><b>{v.order_count}</b><br/>OS</div></div><div className="mt-4 flex gap-2 border-t border-black/6 pt-4"><button className="secondaryButton" onClick={()=>setHistory(v.id)}><History className="size-4"/> Histórico</button>{canWrite&&<button className="secondaryButton" onClick={()=>setEditing(v)}><Edit3 className="size-4"/> Editar</button>}{userRole==="admin"&&v.order_count===0&&v.appointment_count===0&&<button className="secondaryButton text-red-600" disabled={busy} onClick={()=>void remove(v)}><Trash2 className="size-4"/></button>}</div></article>)}</div>{editing&&<VehicleModal vehicle={editing.id?editing:null} busy={busy} onClose={()=>setEditing(null)} onSave={save}/>} {history&&<VehicleHistory id={history} onClose={()=>setHistory(null)} onOpenOrder={id=>{setHistory(null);onOpenOrder(id)}}/>}</div>
}

function VehicleModal({vehicle,busy,onClose,onSave}:{vehicle:any|null;busy:boolean;onClose:()=>void;onSave:(f:VehicleInput)=>Promise<void>}){const {data:customers=[]}=useCustomers();const [f,setF]=useState<VehicleInput>(vehicle?{...blank,...vehicle,customer_id:vehicle.customer_id??vehicle.customers?.id??""}:blank);const set=(k:keyof VehicleInput,v:any)=>setF(x=>({...x,[k]:v}));return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/65 p-4"><div className="mx-auto my-8 max-w-4xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#B97900]">Veículos</p><h2 className="text-2xl font-black">{vehicle?"Editar veículo":"Novo veículo"}</h2></div><button onClick={onClose}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold sm:col-span-2">Proprietário *<select className="field mt-1.5" value={f.customer_id} onChange={e=>set('customer_id',e.target.value)}><option value="">Selecione...</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</select></label>{([['plate','Placa *'],['brand','Marca *'],['model','Modelo *'],['version','Versão'],['year','Ano'],['model_year','Ano modelo'],['color','Cor'],['fuel','Combustível'],['vin','Chassi / VIN'],['current_mileage','Quilometragem']] as [keyof VehicleInput,string][]).map(([k,l])=><label key={k} className="text-sm font-bold">{l}<input className="field mt-1.5" value={String(f[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}</div><label className="mt-3 block text-sm font-bold">Observações<textarea className="field mt-1.5 min-h-24" value={String(f.notes??"")} onChange={e=>set('notes',e.target.value)}/></label><div className="mt-5 flex justify-end gap-2"><button className="secondaryButton" onClick={onClose}>Cancelar</button><button className="goldButton" disabled={busy||!f.customer_id||!f.plate.trim()||!f.brand.trim()||!f.model.trim()} onClick={()=>void onSave(f)}>{busy&&<Loader2 className="size-4 animate-spin"/>} Salvar</button></div></div></div>}

function VehicleHistory({id,onClose,onOpenOrder}:{id:string;onClose:()=>void;onOpenOrder:(id:string)=>void}){const {data,isLoading}=useVehicleHistory(id);return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/65 p-4"><div className="mx-auto my-8 max-w-4xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">Histórico do veículo</h2><button onClick={onClose}><X/></button></div>{isLoading?<p className="mt-5">Carregando...</p>:data?<div className="mt-5 space-y-5"><div><h3 className="text-xl font-black">{(data.vehicle as any).brand} {(data.vehicle as any).model}</h3><p className="text-sm text-black/50">{(data.vehicle as any).plate} • {(data.vehicle as any).customers?.name}</p></div><div><h4 className="font-black">Ordens de serviço</h4><div className="mt-2 space-y-2">{data.orders.map((o:any)=><button key={o.id} onClick={()=>onOpenOrder(o.id)} className="flex w-full justify-between rounded-xl border border-black/8 p-3 text-left"><span>OS #{o.order_number} • {STATUS_LABEL[o.status as OrderStatus]??o.status}</span><b>{money(Number(o.total??0))}</b></button>)}</div></div><div><h4 className="font-black">Agendamentos</h4><div className="mt-2 space-y-2">{data.appointments.map((a:any)=><div key={a.id} className="rounded-xl bg-black/[.03] p-3 text-sm">{new Date(a.scheduled_at).toLocaleString("pt-BR")} • {a.status}</div>)}</div></div></div>:<p className="mt-5">Sem dados.</p>}</div></div>}
