import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Loader2, PackagePlus, Plus, Trash2, TriangleAlert, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { money, useInventory } from "@/lib/porfirid-queries";
import { addInventoryPartToWorkOrder, removeInventoryPartFromWorkOrder } from "@/lib/porfirid-inventory-operations";
import { addManualLabor, addManualPart, removeManualLabor, removeManualPart } from "@/lib/work-order-manual-items";
const db=supabase as any;
export function WorkOrderPartsPanel({workOrderId,parts,locked=false}:{workOrderId:string;parts:any[];locked?:boolean}){
 const queryClient=useQueryClient();const {data:inventory=[]}=useInventory();const {data:manualLabor=[]}=useQuery({queryKey:["work_order_manual_labor",workOrderId],queryFn:async()=>{const {data,error}=await db.from("work_order_services").select("id,service_id,description,quantity,unit_price").eq("work_order_id",workOrderId).is("service_id",null).order("created_at");if(error)throw error;return data??[]}});
 const [selectedId,setSelectedId]=useState(""),[quantity,setQuantity]=useState(1),[unitPrice,setUnitPrice]=useState(0),[manualPart,setManualPart]=useState({description:"",quantity:1,unitPrice:0}),[labor,setLabor]=useState({description:"",quantity:1,unitPrice:0}),[working,setWorking]=useState(false),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
 const selectedItem=useMemo(()=>inventory.find((item:any)=>item.id===selectedId)??null,[inventory,selectedId]);const availableInventory=useMemo(()=>inventory.filter((item:any)=>item.active&&Number(item.quantity)>0),[inventory]);useEffect(()=>{if(selectedItem)setUnitPrice(Number((selectedItem as any).sale_price??0))},[selectedItem]);
 async function refresh(){await Promise.all([queryClient.invalidateQueries({queryKey:["work_order_detail",workOrderId]}),queryClient.invalidateQueries({queryKey:["work_order_manual_labor",workOrderId]}),queryClient.invalidateQueries({queryKey:["inventory_items"]}),queryClient.invalidateQueries({queryKey:["dashboard"]}),queryClient.invalidateQueries({queryKey:["finance"]})])}
 async function run(action:()=>Promise<unknown>,success:string){setWorking(true);setMessage(null);try{await action();await refresh();setMessage({type:"success",text:success})}catch(error){setMessage({type:"error",text:error instanceof Error?error.message:"Não foi possível concluir a ação."})}finally{setWorking(false)}}
 async function addStockPart(){if(!selectedItem)return setMessage({type:"error",text:"Selecione uma peça do estoque."});if(quantity<=0)return setMessage({type:"error",text:"Informe uma quantidade maior que zero."});await run(async()=>{await addInventoryPartToWorkOrder({workOrderId,inventoryItemId:(selectedItem as any).id,quantity,unitPrice});setSelectedId("");setQuantity(1);setUnitPrice(0)},"Peça lançada e baixada do estoque.")}
 async function addFreePart(){await run(async()=>{await addManualPart({workOrderId,description:manualPart.description,quantity:manualPart.quantity,unitPrice:manualPart.unitPrice});setManualPart({description:"",quantity:1,unitPrice:0})},"Peça manual adicionada à OS.")}
 async function addLabor(){await run(async()=>{await addManualLabor({workOrderId,description:labor.description,quantity:labor.quantity,unitPrice:labor.unitPrice});setLabor({description:"",quantity:1,unitPrice:0})},"Mão de obra adicionada à OS.")}
 async function removePart(part:any){await run(()=>part.inventory_item_id?removeInventoryPartFromWorkOrder(part.id):removeManualPart(part.id),part.inventory_item_id?"Peça removida e devolvida ao estoque.":"Peça manual removida.")}
 return <div className="space-y-6">{message&&<p className={`rounded-xl px-3 py-2.5 text-sm font-semibold ${message.type==="error"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{message.text}</p>}
 {!locked&&<section className="rounded-2xl border border-[#F0B323]/20 bg-[#F0B323]/[0.035] p-4"><div className="mb-3"><p className="font-black">Adicionar peça manualmente</p><p className="mt-1 text-xs text-black/45">Use este campo mesmo que a peça não esteja cadastrada no estoque.</p></div><div className="grid gap-3 md:grid-cols-[1.7fr_0.45fr_0.75fr_auto] md:items-end"><Field label="Descrição da peça"><input value={manualPart.description} onChange={e=>setManualPart({...manualPart,description:e.target.value})} placeholder="Ex.: Pastilha de freio dianteira" className="field"/></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" value={manualPart.quantity} onChange={e=>setManualPart({...manualPart,quantity:Number(e.target.value)})} className="field"/></Field><Field label="Valor unit."><input type="number" min="0" step="0.01" value={manualPart.unitPrice} onChange={e=>setManualPart({...manualPart,unitPrice:Number(e.target.value)})} className="field"/></Field><button disabled={working||!manualPart.description.trim()} onClick={()=>void addFreePart()} className="goldButton"><Plus className="size-4"/>Adicionar peça</button></div></section>}
 {!locked&&availableInventory.length>0&&<section className="rounded-2xl border border-black/6 bg-[#fafafa] p-4"><p className="mb-3 text-sm font-black">Ou lançar peça cadastrada no estoque</p><div className="grid gap-3 md:grid-cols-[1.7fr_0.45fr_0.75fr_auto] md:items-end"><Field label="Peça / insumo"><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="field"><option value="">Selecione...</option>{availableInventory.map((item:any)=><option key={item.id} value={item.id}>{item.name} • {Number(item.quantity)} {item.unit} disponíveis</option>)}</select></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="field"/></Field><Field label="Preço unit."><input type="number" min="0" step="0.01" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))} className="field"/></Field><button disabled={working||!selectedId} onClick={()=>void addStockPart()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#17181A] px-4 py-3 text-sm font-black text-white disabled:opacity-50">{working?<Loader2 className="size-4 animate-spin"/>:<PackagePlus className="size-4"/>}Lançar</button></div>{selectedItem&&Number((selectedItem as any).quantity)<=Number((selectedItem as any).min_quantity)&&<p className="mt-3 inline-flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800"><TriangleAlert className="size-4"/>Estoque mínimo: {Number((selectedItem as any).quantity)} {(selectedItem as any).unit}.</p>}</section>}
 <section><p className="mb-3 font-black">Peças da OS</p>{parts.length===0?<p className="text-sm text-black/45">Nenhuma peça lançada.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-black/7 text-[11px] font-bold uppercase tracking-wider text-black/35"><th className="pb-3">Peça</th><th className="pb-3">Qtd.</th><th className="pb-3">Valor unit.</th><th className="pb-3">Total</th><th className="pb-3">Origem</th><th className="pb-3">Ação</th></tr></thead><tbody>{parts.map(part=><tr key={part.id} className="border-b border-black/5 last:border-0"><td className="py-3 font-bold">{part.description}</td><td>{Number(part.quantity)}</td><td>{money(Number(part.unit_price??0))}</td><td className="font-black">{money(Number(part.quantity)*Number(part.unit_price))}</td><td className="text-xs text-black/40">{part.inventory_item_id?"Estoque":"Manual"}</td><td>{locked?<span className="text-xs text-black/35">Fechado</span>:<button disabled={working} onClick={()=>void removePart(part)} className="inline-flex items-center gap-1 rounded-lg border border-black/10 px-2.5 py-1.5 text-xs font-bold text-red-700"><Trash2 className="size-3.5"/>Remover</button>}</td></tr>)}</tbody></table></div>}</section>
 <section className="border-t border-black/7 pt-5"><div className="flex items-center gap-2"><Wrench className="size-4 text-[#B97900]"/><p className="font-black">Mão de obra</p></div>{!locked&&<div className="mt-3 grid gap-3 rounded-2xl bg-[#fafafa] p-4 md:grid-cols-[1.7fr_0.45fr_0.75fr_auto] md:items-end"><Field label="Descrição"><input value={labor.description} onChange={e=>setLabor({...labor,description:e.target.value})} placeholder="Ex.: Mão de obra troca de freios" className="field"/></Field><Field label="Qtd."><input type="number" min="0.01" step="0.01" value={labor.quantity} onChange={e=>setLabor({...labor,quantity:Number(e.target.value)})} className="field"/></Field><Field label="Valor"><input type="number" min="0" step="0.01" value={labor.unitPrice} onChange={e=>setLabor({...labor,unitPrice:Number(e.target.value)})} className="field"/></Field><button disabled={working||!labor.description.trim()} onClick={()=>void addLabor()} className="goldButton"><Plus className="size-4"/>Adicionar</button></div>}{manualLabor.length>0&&<div className="mt-3 space-y-2">{manualLabor.map((item:any)=><div key={item.id} className="flex flex-col gap-2 rounded-xl border border-black/6 bg-white px-3 py-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-sm font-bold">{item.description}</p><p className="text-xs text-black/42">{Number(item.quantity)} × {money(Number(item.unit_price))}</p></div><strong>{money(Number(item.quantity)*Number(item.unit_price))}</strong>{!locked&&<button disabled={working} onClick={()=>void run(()=>removeManualLabor(item.id),"Mão de obra removida.")} className="rounded-lg border border-black/10 p-2 text-red-700"><Trash2 className="size-3.5"/></button>}</div>)}</div>}</section></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5 text-sm font-semibold"><span>{label}</span>{children}</label>}
