import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Camera, CheckCircle2, CreditCard, Loader2, Plus, RefreshCw, Trash2, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { money, ORDER_STATUSES, STATUS_LABEL, type OrderStatus } from "@/lib/porfirid-queries";

const db=supabase as any;
export function WorkOrderDetail({orderId,onBack}:{orderId:string;onBack:()=>void}){
 const [order,setOrder]=useState<any>(null),[services,setServices]=useState<any[]>([]),[parts,setParts]=useState<any[]>([]),[photos,setPhotos]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const [o,s,p,ph,pay]=await Promise.all([db.from("work_orders").select("*, customers(*), vehicles(*)").eq("id",orderId).single(),db.from("work_order_services").select("*").eq("work_order_id",orderId).order("created_at"),db.from("work_order_parts").select("*").eq("work_order_id",orderId).order("created_at"),db.from("vehicle_photos").select("*").eq("work_order_id",orderId).order("created_at"),db.from("payments").select("*").eq("work_order_id",orderId).order("created_at")]);if(o.error)throw o.error;setOrder(o.data);setServices(s.data??[]);setParts(p.data??[]);setPhotos(ph.data??[]);setPayments(pay.data??[])}catch(e:any){setError(e.message??"Erro ao carregar OS") }finally{setLoading(false)}}
 useEffect(()=>{void load()},[orderId]);
 const paid=payments.filter(p=>["confirmado","pago"].includes(p.status)).reduce((s,p)=>s+Number(p.amount||0),0); const balance=Math.max(Number(order?.total||0)-paid,0);
 async function updateStatus(status:OrderStatus){setSaving(true);const {error}=await db.from("work_orders").update({status,delivered_at:status==="entregue"?new Date().toISOString():order.delivered_at}).eq("id",orderId);setSaving(false);if(error)return setError(error.message);await load()}
 async function addLine(kind:"part"|"service"){const description=window.prompt(kind==="part"?"Descrição da peça":"Descrição do serviço");if(!description)return;const price=Number(window.prompt("Valor unitário","0")||0);const table=kind==="part"?"work_order_parts":"work_order_services";const payload=kind==="part"?{work_order_id:orderId,description,quantity:1,unit_price:price,unit_cost:0}:{work_order_id:orderId,description,quantity:1,unit_price:price,cost_price:0,status:"pendente"};const {error}=await db.from(table).insert(payload);if(error)return setError(error.message);await load()}
 async function removeLine(table:string,id:string){if(!confirm("Remover este item da OS?"))return;const {error}=await db.from(table).delete().eq("id",id);if(error)return setError(error.message);await load()}
 async function addPayment(){const amount=Number(window.prompt("Valor recebido",String(balance||0))||0);if(amount<=0)return;const method=window.prompt("Forma de pagamento","PIX")||"PIX";const {error}=await db.from("payments").insert({work_order_id:orderId,amount,method,status:"confirmado",paid_at:new Date().toISOString()});if(error)return setError(error.message);await load()}
 async function upload(files:FileList|null){if(!files?.length||!order?.vehicle_id)return;setSaving(true);for(const file of Array.from(files)){const path=`${orderId}/execucao/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("vehicle-photos").upload(path,file);if(up.error){setError(up.error.message);continue}await db.from("vehicle_photos").insert({work_order_id:orderId,vehicle_id:order.vehicle_id,photo_type:"execucao",storage_path:path,caption:file.name});}setSaving(false);await load()}
 if(loading)return <div className="rounded-2xl bg-white p-10 text-center"><Loader2 className="mx-auto size-6 animate-spin text-[#B97900]"/></div>;if(error&&!order)return <div className="rounded-2xl bg-red-50 p-5 text-red-700">{error}<button onClick={onBack} className="ml-3 underline">Voltar</button></div>;
 const customer=order.customers,vehicle=order.vehicles;
 return <div className="space-y-5"><div className="flex flex-col gap-4 rounded-3xl bg-[#111214] p-6 text-white sm:flex-row sm:items-center"><button onClick={onBack} className="rounded-xl border border-white/10 p-3"><ArrowLeft className="size-5"/></button><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.18em] text-[#F0B323]">Ordem de serviço</p><h2 className="mt-1 text-3xl font-black">OS #{order.order_number}</h2><p className="mt-2 text-sm text-white/50">{customer?.name} • {vehicle?`${vehicle.brand} ${vehicle.model} • ${vehicle.plate}`:"Veículo"}</p></div><div className="text-right"><p className="text-xs text-white/40">Total</p><p className="text-2xl font-black text-[#FFC43D]">{money(Number(order.total||0))}</p></div></div>
 {error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
 <div className="grid gap-4 xl:grid-cols-[1.6fr_.8fr]"><div className="space-y-4"><Card title="Status da OS" icon={RefreshCw}><div className="flex flex-wrap gap-2">{ORDER_STATUSES.map(status=><button disabled={saving} key={status} onClick={()=>void updateStatus(status)} className={`rounded-xl px-3 py-2 text-xs font-black ${order.status===status?"bg-[#F0B323] text-black":"border border-black/10 bg-white text-black/55"}`}>{STATUS_LABEL[status]}</button>)}</div></Card>
 <Card title="Peças" icon={Plus} action={<button onClick={()=>void addLine("part")} className="goldButton"><Plus className="size-4"/>Adicionar</button>}>{parts.length?parts.map(x=><Line key={x.id} row={x} onRemove={()=>void removeLine("work_order_parts",x.id)}/>):<Empty text="Nenhuma peça lançada."/>}</Card>
 <Card title="Mão de obra / serviços" icon={Wrench} action={<button onClick={()=>void addLine("service")} className="goldButton"><Plus className="size-4"/>Adicionar</button>}>{services.length?services.map(x=><Line key={x.id} row={x} onRemove={()=>void removeLine("work_order_services",x.id)}/>):<Empty text="Nenhum serviço lançado."/>}</Card>
 <Card title="Fotos da OS" icon={Camera} action={<label className="goldButton cursor-pointer"><Camera className="size-4"/>Enviar fotos<input type="file" multiple accept="image/*" className="hidden" onChange={e=>void upload(e.target.files)}/></label>}>{photos.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map(p=><Photo key={p.id} photo={p}/>)}</div>:<Empty text="Nenhuma foto registrada."/>}</Card></div>
 <div className="space-y-4"><Card title="Cliente e veículo" icon={CheckCircle2}><Info label="Cliente" value={customer?.name}/><Info label="Telefone" value={customer?.phone}/><Info label="Veículo" value={vehicle?`${vehicle.brand} ${vehicle.model}`:null}/><Info label="Placa" value={vehicle?.plate}/><Info label="KM entrada" value={order.mileage_in?Number(order.mileage_in).toLocaleString("pt-BR")+" km":null}/><Info label="Combustível" value={order.fuel_level}/><Info label="Previsão" value={order.promised_at?new Date(order.promised_at).toLocaleString("pt-BR"):null}/></Card>
 <Card title="Relato e diagnóstico" icon={Wrench}><Info label="Relato do cliente" value={order.customer_report}/><Info label="Diagnóstico" value={order.diagnosis}/><Info label="Observações internas" value={order.internal_notes}/></Card>
 <Card title="Financeiro da OS" icon={CreditCard} action={<button onClick={()=>void addPayment()} className="goldButton"><CreditCard className="size-4"/>Receber</button>}><div className="grid grid-cols-2 gap-3"><Metric label="Total" value={money(Number(order.total||0))}/><Metric label="Recebido" value={money(paid)}/><Metric label="Saldo" value={money(balance)}/><Metric label="Status" value={balance<=0?"Pago":"Pendente"}/></div>{payments.length>0&&<div className="mt-4 space-y-2">{payments.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl bg-black/[.03] p-3 text-xs"><span>{p.method}</span><strong>{money(Number(p.amount||0))}</strong></div>)}</div>}</Card></div></div></div>;
}
function Card({title,icon:Icon,action,children}:{title:string;icon:any;action?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-[#F0B323]/15 text-[#8A5F00]"><Icon className="size-4"/></div><h3 className="flex-1 font-black">{title}</h3>{action}</div>{children}</section>}
function Line({row,onRemove}:{row:any;onRemove:()=>void}){return <div className="mb-2 flex items-center gap-3 rounded-xl bg-black/[.025] p-3"><div className="flex-1"><p className="text-sm font-black">{row.description}</p><p className="mt-1 text-xs text-black/40">{Number(row.quantity||0)} × {money(Number(row.unit_price||0))}</p></div><strong>{money(Number(row.quantity||0)*Number(row.unit_price||0))}</strong><button onClick={onRemove} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="size-4"/></button></div>}
function Info({label,value}:{label:string;value:any}){if(!value)return null;return <div className="border-b border-black/5 py-2 last:border-0"><p className="text-[10px] font-black uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 text-sm font-semibold">{String(value)}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/[.025] p-3"><p className="text-[10px] font-black uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 font-black">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-black/10 p-5 text-center text-sm text-black/40">{text}</div>}
function Photo({photo}:{photo:any}){const [url,setUrl]=useState<string|null>(null);useEffect(()=>{void supabase.storage.from("vehicle-photos").createSignedUrl(photo.storage_path,3600).then(({data})=>setUrl(data?.signedUrl??null))},[photo.storage_path]);return <div className="overflow-hidden rounded-xl border border-black/8 bg-black/[.03]">{url?<img src={url} alt={photo.caption??"Foto"} className="aspect-video w-full object-cover"/>:<div className="aspect-video animate-pulse bg-black/5"/>}<p className="truncate p-2 text-[10px] font-bold">{photo.caption??photo.photo_type}</p></div>}
