import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, Car, ChevronRight, CircleDollarSign, ClipboardList, Gauge, LayoutDashboard, LogOut, Menu, PackageSearch, Plus, ReceiptText, Settings, UserCog, Users, WalletCards, Wrench, X, type LucideIcon } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { BRAND } from "@/lib/brand";

export const Route = createFileRoute("/_authenticated/admin")({
  head: () => ({ meta: [{ title: `Gestão | ${BRAND.name}` }, { name: "description", content: "Painel administrativo completo para oficinas e centros automotivos." }] }),
  component: AdminPage,
});

type ModuleId = "dashboard"|"orders"|"quotes"|"customers"|"vehicles"|"services"|"stock"|"agenda"|"finance"|"reports"|"users"|"settings";
type NavItem = { id:ModuleId; label:string; icon:LucideIcon };
const navItems:NavItem[]=[
  {id:"dashboard",label:"Visão geral",icon:LayoutDashboard},{id:"orders",label:"Ordens de serviço",icon:ClipboardList},{id:"quotes",label:"Orçamentos",icon:ReceiptText},{id:"customers",label:"Clientes",icon:Users},{id:"vehicles",label:"Veículos",icon:Car},{id:"services",label:"Serviços",icon:Wrench},{id:"stock",label:"Estoque e peças",icon:PackageSearch},{id:"agenda",label:"Agenda",icon:CalendarDays},{id:"finance",label:"Financeiro",icon:WalletCards},{id:"reports",label:"Relatórios",icon:BarChart3},{id:"users",label:"Usuários",icon:UserCog},{id:"settings",label:"Configurações",icon:Settings},
];

function AdminPage(){
  const [active,setActive]=useState<ModuleId>("dashboard"); const [mobile,setMobile]=useState(false); const [email,setEmail]=useState("Equipe COMPACT"); const navigate=useNavigate();
  useEffect(()=>{void supabase.auth.getUser().then(({data})=>{if(data.user?.email)setEmail(data.user.email)}).catch(()=>{})},[]);
  async function signOut(){await supabase.auth.signOut();navigate({to:"/login",replace:true})}
  const current=navItems.find(i=>i.id===active)??navItems[0]!;
  return <div className="min-h-screen bg-[#f4f5f7] text-[#17181A]">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col border-r border-white/8 bg-[#09090a] text-white lg:flex"><BrandPanel/><Navigation active={active} setActive={setActive}/><UserPanel email={email} signOut={signOut}/></aside>
    {mobile&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/60" onClick={()=>setMobile(false)}/><aside className="relative flex h-full w-[86%] max-w-80 flex-col bg-[#09090a] text-white"><div className="flex items-center justify-between"><BrandPanel/><button className="mr-4 p-2" onClick={()=>setMobile(false)}><X/></button></div><Navigation active={active} setActive={(m)=>{setActive(m);setMobile(false)}}/><UserPanel email={email} signOut={signOut}/></aside></div>}
    <main className="lg:pl-72"><header className="sticky top-0 z-30 border-b border-black/6 bg-white/90 backdrop-blur-xl"><div className="flex h-20 items-center gap-4 px-4 sm:px-6 lg:px-8"><button onClick={()=>setMobile(true)} className="rounded-xl border border-black/10 p-2 lg:hidden"><Menu className="size-5"/></button><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-[.2em] text-[#B97900]">Gestão da oficina</p><h1 className="truncate text-2xl font-black">{current.label}</h1></div><button onClick={signOut} className="inline-flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2 text-sm font-bold"><LogOut className="size-4"/><span className="hidden sm:inline">Sair</span></button></div></header><section className="p-4 sm:p-6 lg:p-8"><ModuleSwitch active={active}/></section></main>
  </div>
}

function BrandPanel(){return <div className="flex h-20 items-center gap-3 px-5"><img src={BRAND.iconUrl} alt="" className="size-12 rounded-2xl object-contain"/><div><p className="text-lg font-black compact-gold-text">COMPACT</p><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/40">Centro Automotivo</p></div></div>}
function Navigation({active,setActive}:{active:ModuleId;setActive:(m:ModuleId)=>void}){return <nav className="flex-1 space-y-1 overflow-y-auto px-4 py-4">{navItems.map(item=>{const Icon=item.icon;const on=active===item.id;return <button key={item.id} onClick={()=>setActive(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold transition ${on?"bg-[#F0B323] text-black":"text-white/62 hover:bg-white/7 hover:text-white"}`}><Icon className="size-5"/><span className="flex-1">{item.label}</span>{on&&<ChevronRight className="size-4"/>}</button>})}</nav>}
function UserPanel({email,signOut}:{email:string;signOut:()=>void}){return <div className="border-t border-white/8 p-4"><div className="rounded-2xl bg-white/[.04] p-4"><p className="truncate text-sm font-bold">{email}</p><p className="mt-1 text-xs text-white/35">Usuário autenticado</p><button onClick={signOut} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 py-2 text-xs font-bold text-white/60 hover:border-[#F0B323]/50 hover:text-[#FFC43D]"><LogOut className="size-4"/> Sair</button></div></div>}

function ModuleSwitch({active}:{active:ModuleId}){
  if(active==="dashboard")return <Dashboard/>;
  if(active==="orders")return <WorkOrders/>;
  if(active==="quotes")return <CrudModule title="Orçamentos" table="quotes" icon={ReceiptText} columns={["quote_number","status","subtotal_labor","subtotal_parts","discount","total","valid_until"]}/>;
  if(active==="customers")return <CrudModule title="Clientes" table="customers" icon={Users} columns={["name","phone","email","cpf_cnpj","city","state"]}/>;
  if(active==="vehicles")return <CrudModule title="Veículos" table="vehicles" icon={Car} columns={["plate","brand","model","year","color","current_mileage"]}/>;
  if(active==="services")return <CrudModule title="Catálogo de serviços" table="service_catalog" icon={Wrench} columns={["name","category","base_price","estimated_minutes","active"]}/>;
  if(active==="stock")return <CrudModule title="Estoque e peças" table="inventory_items" icon={PackageSearch} columns={["name","sku","category","quantity","min_quantity","cost_price","sale_price"]}/>;
  if(active==="agenda")return <CrudModule title="Agenda operacional" table="appointments" icon={CalendarDays} columns={["scheduled_at","status","expected_minutes","notes"]}/>;
  if(active==="finance")return <Finance/>;
  if(active==="reports")return <Reports/>;
  if(active==="users")return <UsersModule/>;
  return <SettingsModule/>;
}

function Dashboard(){const [data,setData]=useState({orders:0,customers:0,vehicles:0,revenue:0,open:0});const [loading,setLoading]=useState(true);useEffect(()=>{void (async()=>{try{const [o,c,v]=await Promise.all([supabase.from("work_orders").select("id,status,total",{count:"exact"}),supabase.from("customers").select("id",{count:"exact",head:true}),supabase.from("vehicles").select("id",{count:"exact",head:true})]);const rows=(o.data??[]) as any[];setData({orders:o.count??rows.length,customers:c.count??0,vehicles:v.count??0,open:rows.filter(r=>!["entregue","cancelada"].includes(r.status)).length,revenue:rows.filter(r=>r.status==="entregue").reduce((s,r)=>s+Number(r.total??0),0)});}finally{setLoading(false)}})()},[]);const cards=[{label:"OS abertas",value:data.open,icon:ClipboardList},{label:"Clientes",value:data.customers,icon:Users},{label:"Veículos",value:data.vehicles,icon:Car},{label:"Faturamento entregue",value:money(data.revenue),icon:CircleDollarSign}];return <div className="space-y-6"><div className="rounded-[2rem] bg-[#0b0b0c] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-black uppercase tracking-[.22em] text-[#F0B323]">Central operacional</p><h2 className="mt-2 text-3xl font-black">Visão geral da oficina</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Acompanhe operação, clientes, veículos, ordens de serviço e resultado financeiro em um único lugar.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=><MetricCard key={card.label} {...card} loading={loading}/>)}</div><RecentOrders/></div>}
function MetricCard({label,value,icon:Icon,loading}:{label:string;value:string|number;icon:LucideIcon;loading:boolean}){return <div className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/15 text-[#9B6600]"><Icon className="size-5"/></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-black/38">{label}</p><p className="mt-1 text-3xl font-black">{loading?"—":value}</p></div>}
function RecentOrders(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{void supabase.from("work_orders").select("id,order_number,status,total,entry_at,customers(name),vehicles(plate,brand,model)").order("created_at",{ascending:false}).limit(8).then(({data})=>setRows((data??[]) as any[]))},[]);return <div className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><h3 className="text-lg font-black">Últimas ordens de serviço</h3>{rows.length===0?<Empty text="Nenhuma OS registrada ainda."/>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-black/35"><tr><th className="py-3">OS</th><th>Cliente</th><th>Veículo</th><th>Status</th><th>Total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-black/6"><td className="py-3 font-black text-[#9B6600]">#{r.order_number}</td><td>{r.customers?.name??"—"}</td><td>{r.vehicles?`${r.vehicles.brand} ${r.vehicles.model} • ${r.vehicles.plate}`:"—"}</td><td><Status value={r.status}/></td><td className="font-black">{money(r.total)}</td></tr>)}</tbody></table></div>}</div>}

function WorkOrders(){const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [show,setShow]=useState(false);async function load(){setLoading(true);const {data}=await supabase.from("work_orders").select("id,order_number,status,total,entry_at,customer_report,customers(name),vehicles(plate,brand,model)").order("created_at",{ascending:false});setRows((data??[]) as any[]);setLoading(false)}useEffect(()=>{void load()},[]);return <div className="space-y-5"><ModuleHeader icon={ClipboardList} title="Ordens de serviço" subtitle="Controle do atendimento até a entrega."><button onClick={()=>setShow(true)} className="goldButton"><Plus className="size-4"/> Nova OS</button></ModuleHeader>{loading?<Loading/>:rows.length===0?<Empty text="Nenhuma ordem de serviço cadastrada."/>:<div className="grid gap-3">{rows.map(r=><div key={r.id} className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex items-center gap-2"><span className="text-lg font-black text-[#9B6600]">OS #{r.order_number}</span><Status value={r.status}/></div><p className="mt-2 text-sm font-bold">{r.customers?.name??"Cliente"}</p><p className="mt-1 text-xs text-black/45">{r.vehicles?`${r.vehicles.brand} ${r.vehicles.model} • ${r.vehicles.plate}`:"Veículo não informado"}</p></div><div className="text-right"><p className="text-xl font-black">{money(r.total)}</p><p className="text-xs text-black/40">{formatDate(r.entry_at)}</p></div></div></div>)}</div>}{show&&<NewOrderModal onClose={()=>setShow(false)} onSaved={()=>{setShow(false);void load()}}/>}</div>}
function NewOrderModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [customers,setCustomers]=useState<any[]>([]);const [vehicles,setVehicles]=useState<any[]>([]);const [customerId,setCustomerId]=useState("");const [vehicleId,setVehicleId]=useState("");const [report,setReport]=useState("");const [mileage,setMileage]=useState("");const [saving,setSaving]=useState(false);const filtered=vehicles.filter(v=>v.customer_id===customerId);useEffect(()=>{void Promise.all([supabase.from("customers").select("id,name,phone").order("name"),supabase.from("vehicles").select("id,customer_id,plate,brand,model").order("plate")]).then(([c,v])=>{setCustomers((c.data??[]) as any[]);setVehicles((v.data??[]) as any[])})},[]);async function save(){if(!customerId||!vehicleId)return;setSaving(true);const {error}=await supabase.from("work_orders").insert({customer_id:customerId,vehicle_id:vehicleId,customer_report:report,mileage_in:mileage?Number(mileage):null,status:"recepcao",approval_status:"pendente",payment_status:"pendente",subtotal_parts:0,subtotal_services:0,discount:0,total:0});setSaving(false);if(error){alert(error.message);return}onSaved()}return <Modal title="Nova ordem de serviço" onClose={onClose}><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Cliente" value={customerId} onChange={v=>{setCustomerId(v);setVehicleId("")}} options={customers.map(c=>({value:c.id,label:c.name}))}/><SelectField label="Veículo" value={vehicleId} onChange={setVehicleId} options={filtered.map(v=>({value:v.id,label:`${v.plate} • ${v.brand} ${v.model}`}))}/><Field label="Quilometragem" value={mileage} onChange={setMileage} type="number"/><label className="sm:col-span-2 text-sm font-bold"><span>Relato do cliente</span><textarea value={report} onChange={e=>setReport(e.target.value)} rows={4} className="field mt-2"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="secondaryButton">Cancelar</button><button disabled={saving||!customerId||!vehicleId} onClick={()=>void save()} className="goldButton">{saving?"Salvando...":"Abrir OS"}</button></div></Modal>}

function CrudModule({title,table,icon,columns}:{title:string;table:string;icon:LucideIcon;columns:string[]}){const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");async function load(){setLoading(true);const {data,error}=await supabase.from(table as any).select("*").order("created_at",{ascending:false}).limit(200);if(!error)setRows((data??[]) as any[]);setLoading(false)}useEffect(()=>{void load()},[table]);const filtered=useMemo(()=>{const term=search.toLowerCase().trim();if(!term)return rows;return rows.filter(r=>columns.some(c=>String(r[c]??"").toLowerCase().includes(term)))},[rows,search,columns]);return <div className="space-y-5"><ModuleHeader icon={icon} title={title} subtitle="Dados sincronizados com o Supabase da oficina."/><div className="rounded-2xl border border-black/6 bg-white p-4 shadow-sm"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..." className="field max-w-lg"/></div>{loading?<Loading/>:filtered.length===0?<Empty text={`Nenhum registro em ${title.toLowerCase()}.`}/>:<div className="overflow-x-auto rounded-2xl border border-black/6 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-black/[.025] text-xs uppercase tracking-wider text-black/40"><tr>{columns.map(c=><th key={c} className="px-4 py-3">{humanize(c)}</th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={row.id??i} className="border-t border-black/6">{columns.map(c=><td key={c} className="max-w-64 truncate px-4 py-3">{renderValue(c,row[c])}</td>)}</tr>)}</tbody></table></div>}</div>}

function Finance(){const [payments,setPayments]=useState<any[]>([]);const [expenses,setExpenses]=useState<any[]>([]);useEffect(()=>{void Promise.all([supabase.from("payments").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("expenses").select("*").order("created_at",{ascending:false}).limit(100)]).then(([p,e])=>{setPayments((p.data??[]) as any[]);setExpenses((e.data??[]) as any[])})},[]);const received=payments.filter(p=>p.status==="pago").reduce((s,p)=>s+Number(p.amount??0),0);const spent=expenses.filter(e=>e.status==="pago").reduce((s,e)=>s+Number(e.amount??0),0);return <div className="space-y-5"><ModuleHeader icon={WalletCards} title="Financeiro" subtitle="Recebimentos, despesas e visão de caixa."/><div className="grid gap-4 sm:grid-cols-3"><ValueCard label="Recebido" value={received}/><ValueCard label="Despesas pagas" value={spent}/><ValueCard label="Saldo" value={received-spent}/></div><div className="grid gap-5 xl:grid-cols-2"><SimpleList title="Últimos pagamentos" rows={payments} amountKey="amount"/><SimpleList title="Últimas despesas" rows={expenses} amountKey="amount"/></div></div>}
function Reports(){const [orders,setOrders]=useState<any[]>([]);useEffect(()=>{void supabase.from("work_orders").select("status,total,created_at").then(({data})=>setOrders((data??[]) as any[]))},[]);const total=orders.reduce((s,r)=>s+Number(r.total??0),0);const delivered=orders.filter(r=>r.status==="entregue");return <div className="space-y-5"><ModuleHeader icon={BarChart3} title="Relatórios" subtitle="Indicadores operacionais e comerciais."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total de OS" value={orders.length} icon={ClipboardList} loading={false}/><MetricCard label="OS entregues" value={delivered.length} icon={Car} loading={false}/><MetricCard label="Valor em OS" value={money(total)} icon={CircleDollarSign} loading={false}/><MetricCard label="Ticket médio" value={money(delivered.length?delivered.reduce((s,r)=>s+Number(r.total??0),0)/delivered.length:0)} icon={Gauge} loading={false}/></div></div>}
function UsersModule(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{void supabase.from("profiles").select("id,full_name,role,active,created_at").order("created_at",{ascending:false}).then(({data})=>setRows((data??[]) as any[]))},[]);return <div className="space-y-5"><ModuleHeader icon={UserCog} title="Usuários e acessos" subtitle="Perfis e permissões da equipe."/>{rows.length===0?<Empty text="Nenhum perfil de equipe encontrado."/>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(r=><div key={r.id} className="rounded-2xl border border-black/6 bg-white p-5"><div className="flex size-11 items-center justify-center rounded-xl bg-[#F0B323]/15 font-black text-[#9B6600]">{initials(r.full_name||"U")}</div><p className="mt-4 font-black">{r.full_name||"Usuário"}</p><p className="mt-1 text-sm text-black/45">{r.role}</p><span className={`mt-3 inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${r.active?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{r.active?"Ativo":"Inativo"}</span></div>)}</div>}</div>}
function SettingsModule(){const [form,setForm]=useState<any>({trade_name:"COMPACT Centro Automotivo",company_name:"",cnpj:"",phone:"",whatsapp:"",email:"",website:"",street:"",address_number:"",neighborhood:"",city:"",state:"",zip_code:"",slogan:BRAND.slogan});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{void supabase.from("app_settings").select("*").eq("id",1).maybeSingle().then(({data})=>{if(data)setForm(data)})},[]);async function save(){setSaving(true);setMessage("");const {error}=await supabase.from("app_settings").upsert({...form,id:1});setSaving(false);setMessage(error?error.message:"Configurações salvas.")}const keys=["trade_name","company_name","cnpj","phone","whatsapp","email","website","slogan","street","address_number","neighborhood","city","state","zip_code"];return <div className="space-y-5"><ModuleHeader icon={Settings} title="Configurações da oficina" subtitle="É aqui que cada nova implantação troca os dados da marca e da empresa."/><div className="rounded-2xl border border-black/6 bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{keys.map(k=><Field key={k} label={humanize(k)} value={String(form[k]??"")} onChange={v=>setForm((f:any)=>({...f,[k]:v}))}/>)}</div><div className="mt-6 flex items-center gap-3"><button onClick={()=>void save()} disabled={saving} className="goldButton">{saving?"Salvando...":"Salvar configurações"}</button>{message&&<span className="text-sm font-bold text-black/50">{message}</span>}</div></div></div>}

function ModuleHeader({icon:Icon,title,subtitle,children}:{icon:LucideIcon;title:string;subtitle:string;children?:React.ReactNode}){return <div className="flex flex-col gap-4 rounded-2xl border border-black/6 bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#0b0b0c] text-[#F0B323]"><Icon className="size-6"/></div><div className="flex-1"><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-black/45">{subtitle}</p></div>{children}</div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/65 p-4 backdrop-blur-sm"><button className="fixed inset-0" onClick={onClose}/><div className="relative mx-auto mt-10 max-w-3xl rounded-[2rem] bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={onClose} className="rounded-xl border border-black/10 p-2"><X className="size-5"/></button></div>{children}</div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm font-bold"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="field mt-2"/></label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="text-sm font-bold"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="field mt-2"><option value="">Selecione...</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function ValueCard({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-black/6 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-black/35">{label}</p><p className="mt-2 text-2xl font-black">{money(value)}</p></div>}
function SimpleList({title,rows,amountKey}:{title:string;rows:any[];amountKey:string}){return <div className="rounded-2xl border border-black/6 bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-4 space-y-2">{rows.slice(0,8).map((r,i)=><div key={r.id??i} className="flex items-center justify-between rounded-xl bg-black/[.025] p-3"><div><p className="text-sm font-bold">{r.description||r.method||r.status||"Registro"}</p><p className="text-xs text-black/40">{formatDate(r.created_at)}</p></div><p className="font-black">{money(r[amountKey])}</p></div>)}{rows.length===0&&<p className="text-sm text-black/40">Sem registros.</p>}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-black/12 bg-white p-10 text-center"><p className="font-black">{text}</p><p className="mt-1 text-sm text-black/40">Os dados aparecerão aqui assim que forem cadastrados.</p></div>}
function Loading(){return <div className="rounded-2xl bg-white p-10 text-center font-bold text-black/40">Carregando...</div>}
function Status({value}:{value:string}){const map:any={recepcao:"Recepção",diagnostico:"Diagnóstico",aguardando_aprovacao:"Aguardando aprovação",em_execucao:"Em execução",finalizacao:"Finalização",pronto_entrega:"Pronto",entregue:"Entregue",cancelada:"Cancelada"};return <span className="inline-flex rounded-full bg-[#F0B323]/12 px-2.5 py-1 text-xs font-bold text-[#875a00]">{map[value]??value}</span>}
function money(v:any){return Number(v??0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function formatDate(v:any){if(!v)return"—";try{return new Date(v).toLocaleDateString("pt-BR")}catch{return String(v)}}
function humanize(v:string){const map:any={quote_number:"Número",subtotal_labor:"Mão de obra",subtotal_parts:"Peças",valid_until:"Validade",cpf_cnpj:"CPF/CNPJ",current_mileage:"Quilometragem",base_price:"Preço base",estimated_minutes:"Tempo estimado",min_quantity:"Estoque mínimo",cost_price:"Custo",sale_price:"Venda",scheduled_at:"Data/hora",expected_minutes:"Duração",trade_name:"Nome fantasia",company_name:"Razão social",address_number:"Número",zip_code:"CEP"};return map[v]??v.replaceAll("_"," ")}
function renderValue(key:string,v:any){if(v===null||v===undefined||v==="")return"—";if(typeof v==="boolean")return v?"Sim":"Não";if(["base_price","cost_price","sale_price","subtotal_labor","subtotal_parts","discount","total"].includes(key))return money(v);if(key.includes("_at")||key.includes("date")||key==="valid_until")return formatDate(v);return String(v)}
function initials(v:string){return v.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join("").toUpperCase()}
